Tencent/bk-bcs-saas

.travis.yml, bcs-app/.flake8
=> add flake8 config

bcs-app/frontend/src/views/variable/index.vue
变更点(Changes)
- fix 变量管理模块全选框的问题
=> fix 变量管理模块全选框的问题

bcs-app/backend/utils/lock.py, bcs-app/backend/web_console/constants.py, bcs-app/backend/web_console/pod_life_cycle.py
webconsole clean user pod by ThreadPoolExecutor
=> webconsole clean user pod by ThreadPoolExecutor

bcs-app/backend/web_console/bcs_client/mesos.py
mesos resize add thread executor
=> mesos resize add thread executor

bcs-app/frontend/src/views/cluster/index.css, bcs-app/frontend/src/views/cluster/index.vue
变更点：
集群删除优化
1、当集群内没有节点，可删除时，删除按钮可点击
2、当集群内有节点，不可删除时，删除按钮置灰，鼠标放上去做提示
=> 集群删除优化, 不可删除时，删除按钮置灰，鼠标放上去给提示

.travis.yml, bcs-app/.flake8, bcs-app/backend/apps/application/other_views/templates.py, bcs-app/backend/apps/cluster/views_bk/cluster.py, bcs-app/backend/apps/configuration/mesos/validator.py, bcs-app/backend/apps/configuration/models/k8s.py, bcs-app/backend/apps/configuration/models/mesos.py, bcs-app/backend/apps/configuration/models/template.py, bcs-app/backend/apps/configuration/serializers_new.py, bcs-app/backend/apps/configuration/utils.py, bcs-app/backend/apps/instance/generator.py, bcs-app/backend/apps/resource/views.py, bcs-app/backend/apps/ticket/bkdh.py, bcs-app/backend/apps/ticket/bkdh2.py, bcs-app/backend/apps/verfy/serializers.py, bcs-app/backend/bcs_k8s/authtoken/providers/base.py, bcs-app/backend/bcs_k8s/injectors/base.py, bcs-app/backend/bcs_k8s/kubectl/kubeconfig.py, bcs-app/backend/celery_app/tasks/cluster.py, bcs-app/backend/utils/response.py, bcs-app/backend/utils/serializers.py, bcs-app/manage.py, bcs-app/requirements-dev.txt
fix pep8, add travis flake8 check
=> fix pep8, add travis flake8 check

bcs-app/frontend/src/json/k8s-daemonset.json, bcs-app/frontend/src/json/k8s-secret.json, bcs-app/frontend/src/json/k8s-statefulset.json
变更点(Changes)
修复模块集模板json数据kind字段问题
=> 修复模块集模板json数据kind字段问题

bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/service.vue, bcs-app/frontend/src/views/configuration/k8s-create/tabs.vue
变更点(Changes)
K8S Job去掉标签配置并在Service关联应用暂时隐藏Job
=> K8S Job去掉标签配置并在Service关联应用暂时隐藏Job

bcs-app/frontend/src/components/bk-diff/diff.css, bcs-app/frontend/src/components/bk-diff/index.vue, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/k8s/tmpl-rollupdate.html, bcs-app/frontend/src/views/app/mesos/tmpl-list.html, bcs-app/frontend/src/views/helm/app-detail.vue
=> 优化对比组件，增加无对比数据状态

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/base.py, bcs-app/backend/apps/cluster/views/node_views/operation_apis.py
变更点(Changes)
添加故障节点移除操作
issue： #12
=> feat: add delete not ready node api

bcs-app/frontend/src/json/application.json, bcs-app/frontend/src/json/container.json, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/k8s-create/service.vue, bcs-app/frontend/src/views/configuration/mesos-create/application.vue, bcs-app/frontend/src/views/configuration/mesos-create/header.vue
k8s 模板集创建时，默认为空状态
修复模板集没有权限编辑时，锁状态展示样式问题
修复k8s模板集service由于两个依赖接口不同步导致数据展示异常
mesos模板集资源限制增加request(下限)
=> 模板集问题修复及优化

bcs-app/backend/apps/instance/drivers/base.py
变更点(Changes)
mesos集群实例化资源时，删除剩余资源检查逻辑
=> delete mesos resource_ready check

bcs-app/frontend/.gitignore, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.external.vue
=> 节点列表添加`故障移除`操作

bcs-app/backend/apps/configuration/models/k8s.py
变更点:
查询k8s service信息时，添加service的ports数据
=> add service ports info when list k8s services

bcs-app/frontend/src/views/variable/index.vue
=> 修复变量管理分页的 bug

bcs-app/backend/apps/instance/generator.py, bcs-app/backend/apps/instance/resources/mesos/pod.py, bcs-app/backend/apps/instance/resources/utils.py, bcs-app/backend/apps/instance/utils.py
变更点(Changes)
修复Mesos Application中，healthChecks参数传递异常的问题
=> fix mesos healthChecks logic

bcs-app/frontend/src/json/application.json, bcs-app/frontend/src/json/container.json, bcs-app/frontend/src/views/configuration/mesos-create/application.vue
=> 调整mesos健康检查参数配置

bcs-app/frontend/src/json/application.json, bcs-app/frontend/src/json/container.json, bcs-app/frontend/src/views/configuration/mesos-create/application.vue
=>  调整mesos健康检查参数配置

bcs-app/frontend/package.json, bcs-app/frontend/src/components/ring.vue, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.external.vue
变更点(Changes)
- 增加 `entities ~1.1.1` 依赖，避免 `markdown-it` 出现 `Can't resolve 'entities/maps/entities.json'` 的错误。`markdown-it` 包里本身对 `entities` 的依赖就是 `~1.1.1` 但是由于 其他包的引用，导致安装到 `entities` 的 `2.0.0`，因此手动添加一个 `devDependencies`，让 `entities` 的版本回到 `~1.1.1`。
- 修复节点列表，metric 数据圆环展示不正确的问题
=> add entities ~1.1.1

bcs-app/frontend/src/components/terminal/index.vue
=> 配合接口优化web console 交互

bcs-app/frontend/src/components/bk-diff/index.vue
变更点(Changes)
覆盖 diff del line 的情况
=> 覆盖 diff del line 的情况

bcs-app/backend/apps/resource/views.py
变更点(Changes)
- 排序configmap/secret keys
=> feat: sort the configmap/secret keys

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/configuration/k8s/urls.py, bcs-app/backend/apps/configuration/k8s/views.py, bcs-app/backend/apps/configuration/models/__init__.py, bcs-app/backend/apps/configuration/models/k8s.py, bcs-app/backend/apps/configuration/models/utils.py, bcs-app/backend/apps/configuration/showversion/views.py, bcs-app/backend/apps/instance/generator.py
变更点(Changes)
提供更新K8sStatefulSet的service_tag字段的接口，目的是用户配置service关联StatefulSet的时候，能够自动填充serviceName
=> support update service_tag api for model K8sStatefulSet

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/configuration/k8s/urls.py, bcs-app/backend/apps/configuration/k8s/views.py, bcs-app/backend/apps/configuration/models/__init__.py, bcs-app/backend/apps/configuration/models/k8s.py, bcs-app/backend/apps/configuration/models/utils.py, bcs-app/backend/apps/configuration/showversion/views.py, bcs-app/backend/apps/instance/generator.py, bcs-app/frontend/src/components/terminal/index.vue, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/k8s-create/ingress.vue, bcs-app/frontend/src/views/configuration/k8s-create/ingress/ce/k8s-ingress.vue
变更点(Changes)
1、web-console 增加容器窗口之间通信
2、k8s模板集，挂载名调整长度限制
3、优化ingress 路径组绑定服务交互
4、调整接口url，符合restful规范
=> web-console和模板集调整

bcs-projmgr/frontend/src/views/ProjectManage.vue, bcs-projmgr/pm/build.gradle, bcs-projmgr/pm/common/common-service/src/main/kotlin/com/tencent/devops/common/service/env/Env.kt
=> 修改项目页面跳转逻辑

bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/list.css, bcs-app/frontend/src/views/app/mesos/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
应用模块非模板集滚动升级支持编辑状态和对比状态切换
=> 应用模块非模板集滚动升级支持编辑状态和对比状态切换

bcs-app/frontend/src/json/k8s-deployment.json, bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue
变更点(Changes)
Deployment对minReadySeconds进行兼容处理
=> Deployment对minReadySeconds进行兼容处理

bcs-app/frontend/src/views/app/mixins/mixin-base-instantiation.js, bcs-app/frontend/src/views/configuration/instantiation.vue
变更点(Changes)
修复实例化中不同资源同名导致展示样式问题
=> 修复实例化中不同资源同名导致展示样式问题

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/configuration/k8s/views.py
变更点(Changes)
修复StatefulSet的service_tag更新异常的问题
=> fix StatefulSet's service_tag update error

bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
配置statefulset绑定接口在路由change时不中断
=> 配置statefulset绑定接口在路由change时不中断

bcs-app/backend/apps/configuration/models/k8s.py, bcs-app/backend/apps/configuration/models/template.py, bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/configuration/views.py
变更点(Changes)
创建资源时，返回资源的数据信息，便于前端发起绑定statefulset的请求
=> update for service binding with statefulset logic

bcs-app/backend/apps/configuration/models/k8s.py
变更点(Changes)
当simple=True时，Pod get_res_config返回deploy_tag
=> return deploy_tag in K8sPodResource get_res_config when simple=True

bcs-app/frontend/src/json/k8s-hpa.json, bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
service和statefulset联动处理
=> service和statefulset联动处理

bcs-app/backend/apps/configuration/serializers_new.py
变更点(Changes)
删除service时，不校验Pod相关的资源绑定
=> update template: delete service without checking binding statefulset

bcs-projmgr/frontend/src/components/Header/index.vue
变更点(Changes)
修改文档中心的跳转逻辑xxxx
Fixes #
=> 修改文档中心的跳转逻辑

bcs-app/frontend/src/store/modules/hpa.js, bcs-app/frontend/src/views/configuration/instantiation.vue, bcs-app/frontend/src/views/configuration/k8s-create/configmap.vue, bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/k8s-create/ingress.vue, bcs-app/frontend/src/views/configuration/k8s-create/ingress/ce/k8s-ingress.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/secret.vue, bcs-app/frontend/src/views/configuration/k8s-create/service.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue, bcs-app/frontend/src/views/configuration/k8s-create/tabs.vue, bcs-app/frontend/src/views/configuration/k8sCreate.vue, bcs-app/frontend/src/views/configuration/mesos-create/application.vue, bcs-app/frontend/src/views/configuration/mesos-create/configmap.vue, bcs-app/frontend/src/views/configuration/mesos-create/deployment.vue, bcs-app/frontend/src/views/configuration/mesos-create/secret.vue, bcs-app/frontend/src/views/configuration/mesos-create/service.vue, bcs-app/frontend/src/views/configuration/mesos-create/tabs.vue
变更点(Changes)
模板集支持statesulset绑定service
ingress问题修复
调整tab之间切换为同步模式
HPA
=> 模板集问题修复和优化

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
configmap secret对k8s和mesos进行兼容
=> configmap secret对k8s和mesos进行兼容

bcs-app/backend/apps/instance/utils.py, bcs-app/backend/apps/whitelist_bk.py
变更点(Changes)
enabled_hpa_wlist重命名成enabled_hpa_feature
=> rename enabled_hpa_wlist to enabled_hpa_feature

bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/service.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue, bcs-app/frontend/src/views/configuration/mesos-create/application.vue
变更点(Changes)
k8s&mesos对模板集资源限制优化
修复service与statefulset绑定问题
=> k8s&mesos对模板集资源限制优化 修复service与statefulset绑定问题

bcs-app/frontend/src/components/keyer/index.vue, bcs-app/frontend/src/components/page-counter/index.vue, bcs-app/frontend/src/css/app.css
=> mdtric管理辅助国际化

bcs-app/frontend/src/css/mixins/ellipsis.css, bcs-app/frontend/src/views/mc/operate-audit.css, bcs-app/frontend/src/views/mc/operate-audit.vue
变更点(Changes)
修复 操作审计页面 字段长度超长的显示问题
=> 修复 操作审计页面 字段长度超长的显示问题

bcs-app/frontend/src/views/mc/event-query.css, bcs-app/frontend/src/views/mc/event-query.vue
变更点(Changes)
修复 事件查询页面 字段长度超长的显示问题
=> 修复 事件查询页面 字段长度超长的显示问题

bcs-app/frontend/src/views/cluster/overview.vue
变更点(Changes)
修复集群 metric 百分比数据显示问题
=> 修复集群 metric 百分比数据显示问题

bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js
变更点(Changes)
修复应用实例日志刷新内容重复的问题
=> 修复应用实例日志刷新内容重复的问题

bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
修复资源configmap secret对k8s和mesos接口数据兼容问题
=> 修复资源configmap secret对k8s和mesos接口数据兼容问题

bcs-app/frontend/src/views/resource/ingress.vue
变更点(Changes)
修复：ingress判断k8s和mesos问题
=> 修复：ingress判断k8s和mesos问题

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/components/data-searcher/index.vue, bcs-app/frontend/src/components/selector/index.vue, bcs-app/frontend/src/views/configuration/namespace.vue, bcs-app/frontend/tool/extract-chinese1.js
=> namespace 国际化

bcs-app/frontend/src/views/app/k8s/tmpl-list.html
变更点(Changes)
DaemonSet 去除扩缩容功能按钮
=> DaemonSet 去除扩缩容功能按钮

bcs-app/frontend/src/css/app.css
=> bcs-mesos 宽度调整

bcs-app/frontend/src/store/modules/mesos-template.js
变更点(Changes)
mesos模板集添加获取deployment接口
=> mesos模板集添加获取deployment接口

bcs-app/frontend/src/json/hpa.json
变更点(Changes)
update: 调整mesos hpa json
=> update: 调整mesos hpa json

bcs-app/frontend/src/views/configuration/instantiation.vue, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/mesos-create/header.vue
变更点(Changes)
模板详情页面，点击实例化 到实例化页面后，在实例化页面选中模板页面中当前的版本
=> 模板详情页面，点击实例化 到实例化页面后，在实例化页面选中模板页面中当前的版本

bcs-app/frontend/src/views/app/mesos-state.js, bcs-app/frontend/src/views/app/mesos/tmpl-list.html
变更点(Changes)
MESOS下的application处于Finish状态的调整
=> MESOS下的application处于Finish状态的调整

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/app/mesos/tmpl-instance.html, bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js
=> 社区版 mesos 没有容器日志

bcs-app/frontend/src/store/modules/cluster.js
变更点(Changes)
增加创建集群时根据所属地域获取所属 VPC 信息接口
=> 增加创建集群时根据所属地域获取所属 VPC 信息接口

bcs-app/frontend/src/views/app/k8s/daemonset.vue, bcs-app/frontend/src/views/app/k8s/deployments.vue, bcs-app/frontend/src/views/app/k8s/job.vue, bcs-app/frontend/src/views/app/k8s/statefulset.vue, bcs-app/frontend/src/views/app/mesos/mesos.vue
变更点(Changes)
应用里面的容器的维度查看权限 use => view
=> 应用里面的容器的维度查看权限 use => view

bcs-app/frontend/src/views/app/k8s-state.js, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
k8s job 类型增加 Completed 状态
=> k8s job 类型增加 Completed 状态

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/node/index.vue
=> 节点列表添加复制 ip 功能

bcs-app/frontend/src/components/keyer/index.vue, bcs-app/frontend/src/components/selector/index.vue, bcs-app/frontend/src/mixins/network/mixin-base.js
变更点(Changes)
selector添加meric快捷入口
组件国际化
=> selector添加meric快捷入口&组件国际化

bcs-app/backend/apps/configuration/fixture/template_mesos.py
变更点(Changes)
mesos初始模板resources中增加requests配置
=> update mesos init template resources config

bcs-app/frontend/src/components/keyer/index.vue
变更点(Changes)
组件keyer标签生成器国际化处理
=> 组件keyer标签生成器国际化处理

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/configuration/namespace.vue
=> 命名空间删除增加删除成功提示

bcs-app/frontend/src/components/selector/index.vue
变更点(Changes)
fix: 修复下拉选框强制刷新导致搜索框失焦点
=> fix: 修复下拉选框强制刷新导致搜索框失焦点

bcs-app/frontend/src/views/node/index.css
=> 复制 ip 小屏样式问题修复

bcs-app/backend/utils/authentication.py
变更点(Changes)
add apigw_public_key param in JWTClient is_valid method
=> add apigw_public_key param in JWTClient is_valid method

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/node.css, bcs-app/frontend/src/views/cluster/node.external.vue
=> 集群节点管理页面添加提示

bcs-app/frontend/src/views/app/k8s/daemonset-container.vue, bcs-app/frontend/src/views/app/k8s/daemonset-container2.vue, bcs-app/frontend/src/views/app/k8s/daemonset-instance.vue, bcs-app/frontend/src/views/app/k8s/daemonset-instance2.vue, bcs-app/frontend/src/views/app/k8s/daemonset.vue, bcs-app/frontend/src/views/app/k8s/deployments-container.vue, bcs-app/frontend/src/views/app/k8s/deployments-container2.vue, bcs-app/frontend/src/views/app/k8s/deployments-instance.vue, bcs-app/frontend/src/views/app/k8s/deployments-instance2.vue, bcs-app/frontend/src/views/app/k8s/deployments.vue, bcs-app/frontend/src/views/app/k8s/job-container.vue, bcs-app/frontend/src/views/app/k8s/job-container2.vue, bcs-app/frontend/src/views/app/k8s/job-instance.vue, bcs-app/frontend/src/views/app/k8s/job-instance2.vue, bcs-app/frontend/src/views/app/k8s/job.vue, bcs-app/frontend/src/views/app/k8s/statefulset-container.vue, bcs-app/frontend/src/views/app/k8s/statefulset-container2.vue, bcs-app/frontend/src/views/app/k8s/statefulset-instance.vue, bcs-app/frontend/src/views/app/k8s/statefulset-instance2.vue, bcs-app/frontend/src/views/app/k8s/statefulset.vue, bcs-app/frontend/src/views/app/mesos/container.vue, bcs-app/frontend/src/views/app/mesos/container2.vue, bcs-app/frontend/src/views/app/mesos/instance.vue, bcs-app/frontend/src/views/app/mesos/instance2.vue, bcs-app/frontend/src/views/app/mesos/mesos.vue, bcs-app/frontend/src/views/app/mixins/mixin-base-container.js, bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
非模板集创建的应用实例所有操作加上集群 id 参数
=> 非模板集创建的应用实例所有操作加上集群 id 参数

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/images/link-disabled.svg, bcs-app/frontend/src/images/link.svg, bcs-app/frontend/src/views/configuration/instantiation.vue
=> 实例化时新建命名空间

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/configuration/instantiation.css, bcs-app/frontend/src/views/configuration/instantiation.vue
=> 模板实例化页面添加说明文案

bcs-app/backend/apps/application/all_views/k8s_views.py, bcs-app/backend/apps/application/all_views/mesos_views.py, bcs-app/backend/apps/application/utils.py, bcs-app/backend/apps/application/views.py, bcs-app/backend/apps/instance/constants.py, bcs-app/backend/bcs_k8s/app/bcs_info_provider.py
=> Update label and annotations

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/mixins/network/mixin-base.js, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/ingress.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
关于configmap/secret/ingress/service删除时，带上集群、命名空间信息
=> 关于configmap/secret/ingress/service删除时，带上集群、命名空间信息

bcs-app/backend/apps/configuration/yaml_mode/serializers.py
变更点(Changes)
调整返回的show_version的数据结构，方便前端统一处理
=> support yaml template

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/store/modules/k8s-template.js
=> 添加模板集yaml模式接口

bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
添加yaml模板集资源列表支持接口
=> 添加yaml模板集资源列表支持接口

bcs-app/frontend/src/css/bk-patch.css
=> 调整选项卡组件最大宽度

bcs-app/backend/bcs_k8s/app/bcs_info_injector.py, bcs-app/backend/bcs_k8s/app/bcs_info_provider.py
变更点(Changes)
修复重复注入io_tencent_bcs_custom_labels的问题
=> fix duplicate io_tencent_bcs_custom_labels in provide_container_env

bcs-app/frontend/src/api/index.js, bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
修复异常处理多层数据问题
yaml模板集数据保存切换路由不中断
=> 修复异常处理多层数据问题及yaml模板集数据保存切换路由不中断

bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/apps/configuration/namespace/resources/k8s.py, bcs-app/backend/apps/configuration/namespace/resources/mesos.py
=> feat: update app instance api

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/query_apis.py, bcs-app/requirements.txt
=> feat: add export node api

bcs-app/backend/apps/configuration/models/resfile.py
变更点(Changes)
去除yaml配置中镜像的注释部分(如果有)
=> fix yaml template logic

bcs-app/frontend/src/views/metric/index.vue
变更点(Changes)
创建 / 修改 metric，名称最大长度改为 253
=> 创建 / 修改 metric，名称最大长度改为 253

bcs-app/frontend/src/json/k8s-daemonset.json, bcs-app/frontend/src/json/k8s-deployment.json, bcs-app/frontend/src/json/k8s-job.json, bcs-app/frontend/src/json/k8s-statefulset.json
变更点(Changes)
k8s模板集表单模式：卷和挂载卷默认为空
=> k8s模板集表单模式：卷和挂载卷默认为空

bcs-app/backend/apps/metric/serializers.py
=> feat: update metric name

bcs-app/backend/apps/instance/resources/mesos/pod.py
变更点(Changes)
mesos支持COMMAND类型的健康探测
=> support COMMAND healthchecks in mesos

bcs-app/frontend/src/components/keyer/index.vue, bcs-app/frontend/src/json/application.json
变更点(Changes)
修复keyer组件输入事件监听问题
=> 修复keyer组件输入事件监听问题

bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
修复模板集service不断切换发起请求导致数据冲突
=> 修复模板集service不断切换发起请求导致数据冲突

bcs-app/backend/apps/configuration/models/resfile.py, bcs-app/backend/apps/variable/serializers.py
变更点(Changes)
在更新变量key时，增加对key唯一性的校验
=> unique key in Variable when update

bcs-app/frontend/src/store/modules/cluster.js
=> tkc conf 接口

bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
mesos loadbalance 接口调整
=> mesos loadbalance 接口调整

bcs-app/backend/apps/instance/drivers/base.py
=> bugfix: update initial api

bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
调整network lb接口判断mesos/k8s逻辑
=> 调整network lb接口判断mesos/k8s逻辑

bcs-app/backend/apps/cluster/serializers.py
=> bugfix: update cluster

bcs-cc/confcenter/apis/master.go, bcs-cc/confcenter/urlrouter.go, bcs-cc/storage/models/master.go
=> feat: add delete master api

bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js
变更点(Changes)
fix 应用实例详情存活时间计算错误的问题
=> fix 应用实例详情存活时间计算错误的问题

bcs-app/backend/apps/cluster/views_bk/cluster.py, bcs-app/backend/apps/cluster/views_bk/node.py
变更点(Changes)
删除创建set和module相关功能
=> feat: delete cmdb set module api

bcs-app/backend/components/paas_cc.py
变更点(Changes)
调整获取节点api，默认获取全量数据
=> feat: update node list api

bcs-cc/Gopkg.lock, bcs-cc/Gopkg.toml, bcs-cc/components/auth/authtoken.go, bcs-cc/components/bcs/k8s.go, bcs-cc/components/bcs/mesos.go, bcs-cc/confcenter/apis/node.go, bcs-cc/confcenter/tasks/node.go, bcs-cc/confcenter/urlrouter.go, bcs-cc/config/base.go, bcs-cc/config/bcsconf.go, bcs-cc/utils/constants.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/.travis.yml, bcs-cc/vendor/gopkg.in/fatih/set.v0/LICENSE.md, bcs-cc/vendor/gopkg.in/fatih/set.v0/README.md, bcs-cc/vendor/gopkg.in/fatih/set.v0/examples/add_non_thread_safe/main.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/examples/add_thread_safe/main.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set_nots.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set_nots_test.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set_test.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set_ts.go, bcs-cc/vendor/gopkg.in/fatih/set.v0/set_ts_test.go
=> Add node task api

bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/instance/drivers/k8s.py, bcs-app/backend/apps/instance/drivers/mesos.py
=> feat: bugfix for i18n

bcs-app/backend/utils/client.py
变更点(Changes)
修复kubeconfig临时文件关闭后被删除的问题
=> fix kubectl not work

bcs-app/frontend/src/components/monaco-editor/editor.js
变更点(Changes)
add monaco-editor
=> add monaco-editor

bcs-app/frontend/src/components/monaco-editor/editor.js
变更点(Changes)
add monaco-editor language worker
=> add monaco-editor language worker

bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/network/utils.py, bcs-app/backend/apps/network/utils_bk.py, bcs-app/backend/apps/network/views/service.py
变更点(Changes)
添加get_svc_access_info函数，支持service查看内部和外部访问方式
=> add get_svc_access_info in service view

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
service 增加类型、集群内/访问列
=> service 增加类型、集群内/访问列

bcs-app/frontend/src/common/lang.js
=> cl5 router 翻译

bcs-app/backend/apps/network/utils_bk.py, bcs-app/backend/apps/network/views/service.py, bcs-app/backend/utils/client.py
变更点(Changes)
fix service没有ports信息时的异常问题
=> fix service access_info bug

bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/ingress.vue, bcs-app/frontend/src/views/resource/secret.vue
=> 资源添加创建提示文案

bcs-app/backend/bcs_k8s/app/bcs_info_injector.py, bcs-app/backend/utils/views.py, bcs-app/locale/en/LC_MESSAGES/django.po, bcs-app/locale/zh-hans/LC_MESSAGES/django.po
变更点(Changes)
支持CronJob注入imagePullSecret
=> support CronJob imagepullSecret in yaml

bcs-app/frontend/src/views/resource/configmap.css, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
configmap转为configMap
configmap和secret兼容数据
=> configmap转为configMap; configmap和secret兼容数据

bcs-app/frontend/src/store/modules/cluster.js
变更点(Changes)
集群 数据使用 prometheus 接口
=> 集群 数据使用 prometheus 接口

bcs-app/frontend/src/store/modules/app.js
变更点(Changes)
fix getAllMuster4AppSearch
=> fix getAllMuster4AppSearch

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/cluster.js
=> 节点列表指标查询接口切换

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/cluster.js
变更点(Changes)
节点数据接入 prometheus
=> 节点数据接入 prometheus

bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
network service 接口兼容
=> network service 接口兼容

bcs-app/frontend/src/common/util.js
变更点(Changes)
fix formatBytes bug
=> fix formatBytes bug

bcs-app/frontend/src/css/bk-patch.css
=> 国际化英文版的按钮添加线条提示

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/app.js
变更点(Changes)
pod 图表数据使用 prometheus
=> pod 图表数据使用 prometheus

bcs-app/backend/apps/configuration/yaml_mode/views.py
变更点(Changes)
模板集yaml模式下支持日志采集下发
=> add datalog logic in yaml mode

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/store/modules/cluster.js
变更点(Changes)
节点数据从prometheus获取；修复应用列表页 loading 样式问题；
=> 节点数据从prometheus获取；修复应用列表页 loading 样式问题；

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/store/modules/app.js
=> pod 视图、容器视图切换

bcs-app/frontend/src/json/k8s-daemonset.json, bcs-app/frontend/src/json/k8s-deployment.json, bcs-app/frontend/src/json/k8s-statefulset.json, bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
模板集表单模式支持hostAliases
=> 模板集表单模式支持hostAliases

bcs-app/backend/apps/cluster/views_bk/cluster.py
变更点(Changes)
修复删除集群时，删除helm release记录
=> bugfix: delete helm release of cluster when delete cluster

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/configuration/k8s/validator.py
=> delete pod affinity json validate

bcs-app/backend/apps/configuration/constants.py, bcs-app/backend/apps/depot/api.py, bcs-app/backend/apps/depot/views.py, bcs-app/backend/components/enterprise/harbor.py
变更点(Changes)
- 按照更新时间排序image tag
- 修复模板集创建PV资源的校验问题
=> sort image tag

bcs-app/backend/apps/configuration/init_data.py, bcs-app/backend/apps/configuration/yaml_mode/views.py
变更点(Changes)
- 使用ugettext_lazy时，调用str()
- 记录yaml模板集创建和更新时的参数
=> fix: call str() when use ugettext_lazy

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/app.js
=> 应用回滚上一版本的接口

bcs-app/backend/accounts/bcs_perm/__init__.py, bcs-app/backend/apps/application/common_views/operation.py, bcs-app/backend/apps/configuration/constants_k8s.py
变更点(Changes)
1. 更新perm删除命名空间接口
2. 修复回滚版本api
3. 更新service对应的type类型
=> bugfix: update perm and rollback api

bcs-app/frontend/src/components/bk-input/index.vue
变更点(Changes)
修复bk-input组件触发两次事件问题
=> 修复bk-input组件触发两次事件问题

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.external.vue
=> 集群节点批量重新添加前端功能

bcs-app/frontend/src/store/modules/network.js
=> clb 增加监听详情接口

bcs-app/backend/apps/cluster/serializers.py, bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/base.py, bcs-app/backend/apps/cluster/views/node_views/operation_apis.py, bcs-app/backend/apps/cluster/views_bk/node.py
=> Batch operate nodes

bcs-app/backend/apps/network/views/ingress/mesos.py
=> feat: add mesos ingress api

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/json/ingress-rule.json, bcs-app/frontend/src/json/ingress.json, bcs-app/frontend/src/store/modules/mesos-template.js
变更点(Changes)
添加mesos ingress接口及初始化json数据
=> 添加mesos ingress接口及初始化json数据

bcs-app/backend/apps/network/views/ingress/mesos.py
变更点(Changes)
针对更新时间排除ingress列表
=> feat: update mesos ingress api

bcs-app/frontend/src/json/ingress-rule.json, bcs-app/frontend/src/json/ingress.json, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
变更点(Changes)
添加ingress 客户端证书ID&& 调整ingress json模板
=> 添加ingress 客户端证书ID&& 调整ingress json模板

bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
变更点(Changes)
mesos ingress 展示CLB内容及所namespace传给接口
=> mesos ingress 展示CLB内容及所namespace传给接口

bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
=> 调整探测间隔时间限制

bcs-app/frontend/src/components/bk-input/index.vue
=> 修复input控件没有改变问题

bcs-app/frontend/src/components/app-header.vue
变更点(Changes)
mesos ingress hpa添加项目改变时重定向到模板集首页
=> mesos ingress hpa添加项目改变时重定向到模板集首页

bcs-app/frontend/src/components/bk-input/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
变更点(Changes)
调整input的检测时长及mesos ingress 文案更新
=> 调整input的检测时长及mesos ingress 文案更新

bcs-app/frontend/src/views/variable/index.vue
=> 变量批量编辑时增加集群列

bcs-app/frontend/src/store/modules/cluster.js
=> k8s 创建集群时支持版本选择

bcs-app/backend/bcs_k8s/app/serializers.py
变更点(Changes)
增加当前的helm chart内容，方便前端渲染
=> feat: update helm diff content

bcs-app/frontend/src/components/bk-input/index.vue
变更点(Changes)
修复bk-input, 支持id匹配为string和整数
=> 修复bk-input, 支持id匹配为string和整数

bcs-app/frontend/src/components/bk-input/index.vue
变更点(Changes)
调整bk-input的事件触发时机
=> 调整bk-input的事件触发时机

bcs-app/backend/apps/metric/serializers.py, bcs-app/backend/apps/metric/urls_new.py, bcs-app/backend/apps/metric/views/base.py, bcs-app/backend/apps/metric/views/performance.py, bcs-app/backend/apps/metric/views/servicemonitor.py, bcs-app/backend/urls.py
- 新增&修改的文件black格式化
- 新增servicemonitor
=> add service monitor

bcs-app/frontend/src/store/index.js, bcs-app/frontend/src/store/modules/metric.js
=> 自定义 metric

bcs-app/backend/apps/cluster/views_bk/cluster.py, bcs-app/backend/apps/instance/constants.py, bcs-app/backend/apps/resource/views.py
变更点(Changes)
适配mesos存储变更为etcd后，针对名称的调整
=> feat: update mesos rule for etcd

bcs-app/backend/apps/network/views/ingress/mesos.py
变更点(Changes)
更新mesos ingress列表api
=> feat: update clb ingress list api

bcs-app/frontend/src/components/data-searcher/index.vue
变更点(Changes)
更新全局控件data-search, 支持搜索及初始选中
=> 更新全局控件data-search, 支持搜索及初始选中

bcs-app/backend/utils/cc.py
=> bugfix: fix node api

bcs-app/backend/apps/configuration/namespace/serializers.py, bcs-app/backend/bcs_k8s/injectors/base.py, bcs-app/backend/settings/base.py
变更点(Changes)
修复命名空间和helm api的bug
=> bugfix: fix namespace and helm api

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/cluster.py, bcs-app/backend/apps/cluster/views/namespace.py
变更点(Changes)
- 在原有查询集群接口的基础上新增简化查询模式(simple=true)，用于快速返回集群列表
- 新增查询集群下namespace列表的接口，用于快速返回命名空间列表
=> add simple search clusters and namespaces api

bcs-app/backend/apps/configuration/yaml_mode/release.py, bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/helm/bcs_variable.py, bcs-app/backend/bcs_k8s/helm/models/chart.py
=> feat: update bcs system vars

bcs-app/backend/utils/basic.py
变更点(Changes)
add choice_labels and update choice_values in ChoicesEnum
=> add choice_labels and update choice_values in ChoicesEnum

bcs-app/backend/apps/whitelist_bk.py, bcs-app/backend/bcs_k8s/helm/models/chart.py, bcs-app/backend/bcs_k8s/helm/views.py
=> feat: update helm chart overwrite

bcs-app/backend/utils/basic.py
=> feat: add basic api

bcs-app/backend/apps/cluster/views_bk/cluster.py
=> feat: delete namespace perm

bcs-app/frontend/src/store/modules/crdcontroller.js, bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
ingress 兼容tls
调整组件库列表接口, 增加新的接口
=> 调整组件库列表接口, 增加新的接口及ingress 兼容tls

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/node_views/query_apis.py
=> feat: update export node api

bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/apps/application/views.py, bcs-app/backend/apps/datalog/utils.py
=> update get container std logs

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/metric.js
=> 自定义 metric 优化

bcs-app/backend/bcs_k8s/app/views.py
变更点(Changes)
针对helm release添加namespace 搜索
=> feat: add namespace filter

bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/application/views.py, bcs-app/backend/apps/network/views/service.py
变更点(Changes)
1. 禁用sts滚动升级取消操作
2. 调整service 列表api
=> bugfix: update app and service api

bcs-app/frontend/src/components/app-header.vue
变更点(Changes)
fix 切换项目时 metric 集群混乱的问题
=> fix 切换项目时 metric 集群混乱的问题

bcs-app/frontend/src/store/modules/helm.js
=> feat: update front helm api

bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
fix 节点 设置标签功能 bug
=> fix 节点 设置标签功能 bug

bcs-app/backend/apps/instance/generator.py, bcs-app/backend/bcs_k8s/injectors/base.py, bcs-app/backend/bcs_k8s/injectors/constants.py
=> feat: update platform inject info

bcs-app/backend/apps/configuration/models/mesos.py, bcs-app/backend/apps/instance/generator.py
变更点(Changes)
支持mesos模板集在挂载configmap或secret时，指定目录用户
=> support set configmap&secret volumes user in mesos templateset

bcs-app/backend/apps/configuration/models/mesos.py
变更点(Changes)
修复: support set configmap&secret volumes user in mesos templateset
=> fix: support set configmap&secret volumes user in mesos templateset

bcs-app/frontend/src/store/modules/mesos-template.js
=> mesos template

bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/bcs_k8s/helm/views.py
变更点(Changes)
调整chart version展示顺序
=> feat: update helm chart version order

bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/components/data/query.py
变更点(Changes)
get_container_logs函数中新增username参数
=> add username in get_container_logs function

bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/application/constants.py
变更点(Changes)
修复获取k8s pod api接口，添加pod关联的类型参数
=> bugfix: update get pod api

bcs-app/frontend/src/components/data-searcher/index.vue, bcs-app/frontend/src/components/selector/index.vue, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/store/modules/network.js, bcs-app/frontend/src/views/variable/index.vue
变更点(Changes)
1 搜索框支持placeholder
2 service接口调整
=> 搜索框支持placeholder及service接口调整

bcs-app/backend/apps/configuration/models/template.py, bcs-app/backend/utils/views.py
变更点(Changes)
custom_exception_handler返回的500信息中，增加request_id
=> add request_id in 500 response of custom_exception_handler

bcs-app/frontend/src/store/modules/network.js, bcs-app/frontend/src/store/modules/resource.js, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
变更点(Changes)
ingress和loadbalance调整加载方式为第一个集群的数据
=> ingress和loadbalance调整加载方式为第一个集群的数据

bcs-app/backend/apps/network/views/lb/k8s.py, bcs-app/backend/apps/network/views/lb/mesos.py, bcs-app/backend/apps/resource/views_ingress.py
=> feat: add cluster id filter

bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
=> 修复ingress搜索

bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
resource资源分页逻辑调整及文案修改
=> resource资源分页逻辑调整及文案修改

bcs-app/backend/apps/configuration/serializers_new.py, bcs-app/backend/apps/configuration/yaml_mode/release.py, bcs-app/backend/apps/configuration/yaml_mode/res2files.py, bcs-app/backend/apps/configuration/yaml_mode/serializers.py, bcs-app/backend/apps/configuration/yaml_mode/views.py
变更点(Changes)
YAML模板集支持apply时传递模板变量
=> add parameter template_variables in apply yaml templateset api

bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/mesos/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
=> 应用 命名空间批量删除

bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/apps/application/serializers.py
=> feat: update app batch delete api

bcs-app/backend/apps/configuration/namespace/tasks.py, bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/configuration/yaml_mode/release.py
变更点(Changes)
命名空间注册到权限中心时带上集群ID信息
=> change: register namespace(cluster_id) in perm

bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/helm/models/chart.py, bcs-app/backend/bcs_k8s/kubehelm/helm.py, bcs-app/backend/bcs_k8s/kubehelm/templates/inject_bcs_info.yaml, bcs-app/backend/bcs_k8s/utils.py, bcs-app/backend/settings/base.py
=> feat: update helm inject function

bcs-app/frontend/src/store/modules/resource.js, bcs-app/frontend/src/views/node/index.css, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
配置的configmap secret加载方式调整及node样式修复
=> 配置的configmap secret加载方式调整及node样式修复

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/cluster.py, bcs-app/backend/components/bcs/mesos.py
变更点(Changes)
添加查询mesos集群ip pool的api
=> feat: add mesos cluster ippool

bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/bcs_k8s/app/utils.py, bcs-app/backend/bcs_k8s/helm/models/chart.py, bcs-app/backend/bcs_k8s/helm/tasks.py, bcs-app/backend/bcs_k8s/helm/utils/repo.py, bcs-app/backend/bcs_k8s/kubehelm/templates/inject_bcs_info.yaml
=> feat: update sync chart api

bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
mesos 集群 首页 ip 信息
=> mesos 集群 首页 ip 信息

bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/configuration/utils_ns.py, bcs-app/backend/apps/instance/generator.py, bcs-app/backend/components/paas_cc.py
=> support input docker image in pageform templatesets

bcs-app/backend/apps/cluster/constants.py, bcs-app/backend/apps/cluster/views/node.py
变更点(Changes)
标识机器是否为docker机，以便进行过滤
=> feat: update node filter api

bcs-app/backend/bcs_k8s/app/views.py
变更点(Changes)
针对helm namespace过滤，支持是否过滤使用权限
=> feat: update helm ns api

bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/app/views.py
=> Update helm ns api

bcs-app/frontend/src/views/node/index.vue
=> 节点批量设置标签问题修复

bcs-app/backend/apps/constants.py, bcs-app/backend/apps/network/views/service.py, bcs-app/backend/apps/resource/views.py
变更点(Changes)
修复添加命名空间时，校验命名空间名称的异常问题
=> bugfix: update add namespace api validator

bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
适配数据结构中的 task_url
=> 适配数据结构中的 task_url 

bcs-app/frontend/src/views/mc/operate-audit.vue
变更点(Changes)
修复 操作审计 切换 router 后，表格中类型字段数据有时候没有映射的问题
=> 修复 操作审计 切换 router 后，表格中类型字段数据有时候没有映射的问题

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/apps/cluster/views/utils.py
变更点(Changes)
针对集群和节点初始化失败后，添加错误消息
=> feat: add error message for cluster and node

bcs-app/backend/activity_log/client.py, bcs-app/backend/apps/application/views.py
=> bugfix: fix update app api

bcs-app/backend/bcs_k8s/helm/tasks.py
=> feat: update helm chart default version

bcs-app/backend/bcs_k8s/helm/tasks.py
变更点(Changes)
优化同步helm chart版本api
=> bugfix: fix helm sync chart version api

bcs-app/frontend/src/store/modules/variable.js, bcs-app/frontend/src/views/variable/index.css, bcs-app/frontend/src/views/variable/index.vue, bcs-app/frontend/src/views/variable/variable.json
=> 变量支持文件导入功能

bcs-app/backend/apps/application/instance_views.py
变更点(Changes)
修复删除资源出错时，获取资源名称时，key异常问题
=> bugfix: fix the batch delete resource api

bcs-app/backend/apps/application/instance_views.py
=> bugfix: fix the rollingupdate api

bcs-app/backend/apps/cluster/driver/k8s.py, bcs-app/backend/apps/cluster/driver/mesos.py, bcs-app/backend/apps/cluster/models.py, bcs-app/backend/apps/cluster/views/node.py
=> feat: update reschedule node pods

bcs-app/backend/apps/application/views.py
=> feat: update app views api

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/components/bk-input/index.vue, bcs-app/frontend/src/views/variable/index.vue
变更点(Changes)
- 修复bk-input问题
- 变量导入国际化补充
=> 修复bk-input问题及变量导入国际化补充

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/configuration.js, bcs-app/frontend/src/views/configuration/namespace.css, bcs-app/frontend/src/views/configuration/namespace.vue
=> mesos 删除命名空间

bcs-app/backend/apps/configuration/namespace/resources/mesos.py
变更点(Changes)
修复删除namespace的参数异常
=> bugfix: delete mesos namespace api

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/configuration/namespace.css, bcs-app/frontend/src/views/configuration/namespace.vue
变更点(Changes)
mesos 删除命名空间 增加关闭 icon
=> mesos 删除命名空间 增加关闭 icon

bcs-app/frontend/src/components/bk-input/combox.vue, bcs-app/frontend/src/json/k8s-container.json, bcs-app/frontend/src/json/k8s-daemonset.json, bcs-app/frontend/src/json/k8s-deployment.json, bcs-app/frontend/src/json/k8s-job.json, bcs-app/frontend/src/json/k8s-statefulset.json, bcs-app/frontend/src/store/modules/k8s-template.js
=> k8s模板集镜像自定义交互优化

bcs-app/frontend/src/components/bk-input/combox.vue, bcs-app/frontend/src/json/application.json, bcs-app/frontend/src/json/container.json, bcs-app/frontend/src/json/k8s-container.json, bcs-app/frontend/src/json/k8s-daemonset.json, bcs-app/frontend/src/json/k8s-deployment.json, bcs-app/frontend/src/json/k8s-job.json, bcs-app/frontend/src/json/k8s-statefulset.json, bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/store/modules/mesos-template.js
=> mesos镜像自定义优化

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
mesos 集群 ip 资源展示调整
=> mesos 集群 ip 资源展示调整

bcs-app/backend/apps/cluster/constants.py
变更点(Changes)
修复添加节点时，国际化出现异常问题
=> feat: bugfix for add node

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/mixin-node.js
=> mesos 集群节点视图

bcs-app/backend/resources/cluster/utils.py
=> feat: add cluster resource utils

bcs-app/backend/resources/cluster/utils.py
变更点(Changes)
优化集群版本展示顺序，保证优先稳定版本
=> feat: update cluster version

bcs-app/backend/bcs_k8s/app/utils_bk.py, bcs-app/backend/bcs_k8s/app/views.py, bcs-app/backend/bcs_k8s/helm/utils/repo.py
=> Update helm chart repo

bcs-app/backend/bcs_k8s/helm/urls.py, bcs-app/backend/bcs_k8s/helm/views.py, bcs-app/backend/components/helm_chart.py
变更点(Changes)
添加chart或chart版本的删除操作
=> feat: add delete chart api

bcs-app/backend/components/helm_chart.py
=> bugfix: update delete chart api

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/store/modules/helm.js
=> helm增加删除chart和版本

bcs-app/backend/apps/application/base_views.py, bcs-app/backend/utils/errcodes.py
变更点(Changes)
添加针对mesos deployment和application不存在时，状态码的优化
=> feat: update mesos api code

bcs-app/backend/resources/constants.py
=> feat: add k8s resource kind

bcs-app/backend/apps/application/all_views/k8s_views.py, bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/application/utils.py
=> feat: update query app by storage api

bcs-app/backend/resources/cluster/utils.py
=> feat: upgrade bcs k8s cluster version

bcs-app/backend/celery_app/__init__.py
=> feat: update celerybeat task intervals

bcs-app/backend/apps/cluster/models.py
=> feat: add cluster upgrade api

bcs-app/backend/apps/cluster/constants.py, bcs-app/backend/apps/cluster/models.py
=> Upgrade bcs cluster

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/resource/urls.py, bcs-app/backend/apps/resource/views.py
=> bugfix: update ingress api

bcs-app/backend/apps/configuration/k8s/serializers.py, bcs-app/backend/apps/network/urls.py, bcs-app/backend/apps/resource/urls.py
变更点(Changes)
调整ingress api url
=> feat: update ingress api url

bcs-app/frontend/src/store/modules/resource.js, bcs-app/frontend/src/views/resource/ingress.css, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue
变更点(Changes)
resource ingress 增加更新
=> resource ingress 增加更新

bcs-app/frontend/src/views/resource/ingress/k8s/index.vue
=> ingress问题修复

bcs-app/frontend/src/views/resource/ingress/k8s/index.vue
=> ingerss问题修复

bcs-app/backend/apps/resource/views.py
=> bugfix: update k8s resource api

bcs-app/backend/apps/projects/views.py
=> feat: update api for update project

bcs-app/backend/resources/namespace/utils.py
变更点(Changes)
添加同步命名空间需要的resource
=> feat: add sync namespace resource

bcs-app/frontend/src/components/keyer/index.vue
=> bk-keyer增加trim处理

bcs-app/frontend/src/common/path2tree.js
=> 调整路径转树结构函数

bcs-app/frontend/src/views/cluster/create.external.vue
=> mesos 去掉集群分类

bcs-cc/confcenter/apis/project.go, bcs-cc/confcenter/apis/serializers.go, bcs-cc/storage/models/project.go, bcs-cc/storage/models/qs_project_custom.go
=> feat: update bcs cc project api

bcs-app/frontend/src/common/path2tree.js, bcs-app/frontend/src/components/bk-input/index.vue, bcs-app/frontend/src/json/container.json
变更点(Changes)
- 调整path2tree函数
- bkinput增加focus api
=> 调整path2tree函数和bkinput增加focus api

bcs-app/backend/apps/application/instance_views.py
=> feat: update k8s resource api

bcs-app/frontend/src/common/path2tree.js, bcs-app/frontend/src/components/bk-input/index.vue
变更点(Changes)
- 调整path2tree，展开第一个目录节点所有层级
- bk-input组件, 增加enter事件
=> 调整path2tree及bk-input组件

bcs-app/backend/bcs_k8s/helm/views.py
=> feat: update delete chart version api

bcs-app/backend/apps/application/base_views.py
=> feat: update query rs api

bcs-app/backend/apps/cluster/views_bk/configs/mesos.py, bcs-app/backend/apps/cluster/views_bk/node.py
=> feat: update mesos flow config

bcs-app/frontend/src/components/keyer/index.vue, bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
- keyer组件扩展item属性
- network增加区域接口
=> keyer组件扩展item属性及network增加区域接口

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/apps/cluster/views_bk/node.py, bcs-app/backend/components/paas_cc.py
=> feat: update node selector

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/components/bcs/mesos.py, bcs-app/backend/components/paas_cc.py
变更点(Changes)
更新mesos api和设置查询集群为全量集群
=> feat: update mesos api and query cluster api

bcs-app/backend/apps/cluster/views_bk/node.py
变更点(Changes)
更新添加节点api，调整先前传递一个master ip为全部master ip
=> feat: update api for add node

bcs-app/frontend/src/store/modules/app.js
变更点(Changes)
应用 instance pod/taskgroup 三个图表接口改为 post
=> 应用 instance pod/taskgroup 三个图表接口改为 post

bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.external.vue
=> 节点管理增加复制ip功能

bcs-app/backend/bcs_k8s/helm/views.py
变更点(Changes)
调整同步指定仓库时，默认不强制通知chart
=> feat: update repo sync chart api

bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/store/modules/network.js
变更点(Changes)
k8s模板集增加详情接口,用于表单转yaml
=> k8s模板集增加详情接口,用于表单转yaml

bcs-app/backend/bcs_k8s/app/deployer.py, bcs-app/backend/bcs_k8s/kubehelm/helm.py
变更点(Changes)
更新helm install or update时，chart的目录结构
=> feat: update helm3 files structs

bcs-app/backend/apps/instance/constants.py, bcs-app/backend/apps/network/serializers.py, bcs-app/backend/apps/network/utils.py, bcs-app/backend/apps/network/views/lb/mesos.py
=> Update mesos lb image

bcs-app/backend/apps/network/views/lb/mesos.py
=> feat: update mesos lb image

bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/bcs_k8s/app/serializers.py
变更点(Changes)
查询release时，返回cmd flags
=> feat: update helm cmd flags

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js
=> 业务集群公共资源使用|前端支持

bcs-app/backend/resources/cluster/utils.py
=> feat: update get cluster nodes

bcs-app/backend/resources/namespace/utils.py
变更点(Changes)
修复查询命名空间时，组装k8s client参数缺失错误
=> bugfix: fix the api for get namespace

bcs-app/backend/bcs_k8s/helm/tasks.py
变更点(Changes)
修复helm同步chart api时，默认版本不更新问题
=> bufix: fix helm chart sync repo api

bcs-app/backend/apps/metric/views/servicemonitor.py
=> fix namespace permission bug

bcs-app/frontend/src/components/selector/index.vue, bcs-app/frontend/src/css/app.css
变更点(Changes)
修复tree及selector样式问题
=> 修复tree及selector样式问题

bcs-app/backend/apps/cluster/serializers.py, bcs-app/backend/apps/cluster/views_bk/cluster.py, bcs-app/backend/apps/cluster/views_bk/node.py, bcs-app/backend/resources/cluster/utils.py, bcs-cc/confcenter/apis/cluster.go, bcs-cc/confcenter/apis/constants.go, bcs-cc/confcenter/apis/utils.go, bcs-cc/storage/models/cluster.go
=> feat: update cluster type

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/cluster.js
变更点(Changes)
bcs-saas在同一个项目中支持k8s和tke两种集群|前端调整
=> bcs-saas在同一个项目中支持k8s和tke两种集群|前端调整

bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/bcs_k8s/app/views.py
=> feat: update pod status api

bcs-app/frontend/src/css/app.css
变更点(Changes)
调整实例化选择命名空间展示样式,加宽
=> 调整实例化选择命名空间展示样式,加宽

bcs-app/frontend/src/components/resize/index.vue
变更点(Changes)
增加resize组件,用于元素宽度动态改变
=> 增加resize组件,用于元素宽度动态改变

bcs-app/frontend/src/components/data-searcher/index.vue, bcs-app/frontend/src/components/resize/index.vue, bcs-app/frontend/src/views/resource/configmap.vue, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/resource/ingress/mesos/index.vue, bcs-app/frontend/src/views/resource/secret.vue
变更点(Changes)
helm\网络\资源列表支持集群信息缓存
=> helm\网络\资源列表支持集群信息缓存

bcs-app/frontend/src/components/resize/index.vue
变更点(Changes)
增加resize组件触发区隐藏配置
=> 增加resize组件触发区隐藏配置

bcs-app/backend/apps/application/all_views/mesos_views.py
变更点(Changes)
针对mesos，去掉同步storage的功能
=> feat: update mesos sync app api

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/app.js, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js
变更点(Changes)
集群, 节点 metric 调整;应用调整
=> 集群, 节点 metric 调整;应用调整

bcs-app/frontend/src/views/variable/index.vue
=> 变量增加批量编辑文本模式

bcs-app/frontend/src/views/variable/index.vue
=> 变量文本模式调整json格式

bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/utils.py
变更点(Changes)
添加新添加的集群到查询到的命名空间列表
=> feat: add cluster without ns

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/index.vue, bcs-app/frontend/src/views/cluster/mixin-node.js
=> 修复 cluster 小问题

bcs-app/backend/resources/constants.py
变更点(Changes)
WorkloadTypes(ChoicesEnum) 增加 GameStatefulSet
=> add GameStatefulSet to WorkloadTypes(ChoicesEnum)

bcs-app/backend/apps/instance/generator.py, bcs-app/backend/resources/constants.py
变更点(Changes)
mesos配置支持env的valueFrom类型
=> feat: support env valueFrom for mesos manifest

bcs-app/frontend/src/store/modules/k8s-template.js
变更点(Changes)
k8s模板集initcontainer类型兼容健康检查\就绪检查\生命周期
=> k8s模板集initcontainer类型兼容健康检查\就绪检查\生命周期

bcs-cc/confcenter/apis/cluster.go, bcs-cc/confcenter/urlrouter.go
变更点(Changes)
通过cluster id查询集群信息
=> feat: query cluster by cluster id

bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/network/views/service.py
变更点(Changes)
- 修复查询命名空间，集群不存在时的异常
- 修复查询service时，service label中集群ID不存在问题
=> feat: fix ns service bugs

bcs-cc/components/auth/authtoken.go, bcs-cc/components/bcs/k8s.go, bcs-cc/confcenter/tasks/node.go
=> feat: update bcs cc sync nodes

bcs-app/backend/apps/cluster/views/metric_handler/node.py
=> bugfix: fix cluster summary api

bcs-app/frontend/src/views/cluster/mixin-node.js
变更点(Changes)
tke集群 添加节点加host_source参数
=> update: tke集群 添加节点加host_source参数

bcs-app/backend/apps/network/constants.py, bcs-app/backend/apps/network/utils.py, bcs-app/backend/apps/network/views/lb/k8s.py
=> feat: update ingress controller yaml

bcs-app/backend/components/bcs/k8s.py, bcs-app/backend/components/bcs/k8s_client.py, bcs-app/backend/components/bcs/resources/__init__.py, bcs-app/backend/components/bcs/resources/api_response.py, bcs-app/backend/components/bcs/resources/configmap.py, bcs-app/backend/components/bcs/resources/daemonset.py, bcs-app/backend/components/bcs/resources/deployment.py, bcs-app/backend/components/bcs/resources/endpoints.py, bcs-app/backend/components/bcs/resources/event.py, bcs-app/backend/components/bcs/resources/ingress.py, bcs-app/backend/components/bcs/resources/job.py, bcs-app/backend/components/bcs/resources/namespace.py, bcs-app/backend/components/bcs/resources/node.py, bcs-app/backend/components/bcs/resources/pod.py, bcs-app/backend/components/bcs/resources/pv.py, bcs-app/backend/components/bcs/resources/pvc.py, bcs-app/backend/components/bcs/resources/replicaset.py, bcs-app/backend/components/bcs/resources/resource.py, bcs-app/backend/components/bcs/resources/secret.py, bcs-app/backend/components/bcs/resources/service.py, bcs-app/backend/components/bcs/resources/statefulset.py, bcs-app/backend/components/bcs/resources/storageclass.py
变更点(Changes)
去除调用bcs api的driver组件
=> feat: merge bcs k8s api

bcs-app/backend/apps/cluster/views/cluster.py, bcs-app/backend/apps/variable/serializers.py
=> feat: fix some bugs

bcs-app/backend/apps/cluster/views_bk/node.py
=> feat: update add node api

bcs-app/backend/components/bcs/k8s.py, bcs-app/backend/components/bcs/k8s_client.py
=> Merge bcs k8s api

bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.external.vue
变更点(Changes)
修复 集群，节点管理查看日志，没有查看详情
=> 修复 集群，节点管理查看日志，没有查看详情

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/components/bcs/mesos.py, bcs-app/backend/web_console/bcs_client/mesos.py
变更点(Changes)
优化节点disable和enable操作时的日志记录
=> feat: update node enable/disable logs

bcs-app/frontend/src/store/modules/app.js, bcs-app/frontend/src/views/cluster/mixin-node.js
=> update: 添加获取日志查询链接接口

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/node.py
变更点(Changes)
查询集群下的所有节点，用于前端IP复制功能
=> feat: add query cluster nodes api

bcs-app/backend/apps/cluster/serializers.py, bcs-app/backend/apps/cluster/views/node.py
=> feat: add node status filter

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.css, bcs-app/frontend/src/views/cluster/node.external.vue, bcs-app/frontend/src/views/cluster/searcher/index.css, bcs-app/frontend/src/views/cluster/searcher/index.vue, bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
集群下节点支持根据状态进行过滤，支持复制集群下所有节点的IP
=> 集群下节点支持根据状态进行过滤，支持复制集群下所有节点的IP

bcs-app/frontend/src/views/cluster/searcher/index.vue
=> up comment

bcs-app/frontend/src/components/expression/index.vue, bcs-app/frontend/src/store/modules/crdcontroller.js
=> 日志采集支持指定标签

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/network.js
=> up network api

bcs-app/backend/apps/network/constants.py, bcs-app/backend/apps/network/views/charts/versions.py, bcs-app/backend/apps/network/views/lb/k8s.py
=> feat: add ns name for lb api

bcs-app/backend/apps/constants.py, bcs-app/backend/bcs_k8s/kubectl/kubectl.py, bcs-app/backend/utils/client.py, bcs-app/backend/utils/decorators.py
变更点(Changes)
马赛克在request.body中的敏感关键字(请求日志记录时)
=> refactor: mosaic sensitive keyword in request.body when logging curl_log

bcs-app/frontend/src/views/node/index.vue
=> 修复节点搜索组件过滤的问题

bcs-app/frontend/src/views/app/instance.css, bcs-app/frontend/src/views/app/pod-chart-opts.js
=> 应用实例页面图表展示问题修复

bcs-app/backend/bcs_k8s/app/views.py
变更点(Changes)
更新查询helm task任务状态
=> fix: fix helm task api

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/apps/cluster/views/utils.py, bcs-app/backend/resources/cluster/utils.py
=> feat: update cluster apis

bcs-app/frontend/src/components/ace-editor/index.js, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue
变更点(Changes)
- 调整滚动条样式
- 编辑器默认光标位置
- ingress提示优化
=> update: 调整滚动条样式 & 编辑器默认光标位置 & ingress提示优化

bcs-app/backend/apps/projects/views.py
=> refactor: order nav projects by created_at desc

bcs-app/frontend/src/components/data-searcher/index.vue, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/views/variable/index.vue
=> 修复变量批量导入提示报错

bcs-app/backend/components/prometheus.py, bcs-app/backend/utils/decorators.py
=> fix: fix http response

bcs-app/backend/apis/resources/namespace.py, bcs-app/backend/apis/resources/serializers.py, bcs-app/backend/apis/templatesets/form_mode/views.py, bcs-app/backend/resources/project/constants.py
变更点(Changes)
添加命名空间和configmap api
=> feat: add namespace and configmap api

bcs-app/backend/apis/authentication.py, bcs-app/backend/apis/resources/namespace.py, bcs-app/backend/apis/resources/serializers.py
=> fix: fix auth for apis

bcs-app/backend/bcs_k8s/kubectl/kubectl.py, bcs-app/backend/components/bcs/resources/resource.py
变更点(Changes)
修复查询storage class api异常
=> fix: fix sc api

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/configuration/instantiation.vue, bcs-app/frontend/src/views/configuration/k8s-create/configmap.vue, bcs-app/frontend/src/views/configuration/k8s-create/secret.vue, bcs-app/frontend/src/views/configuration/mesos-create/configmap.vue, bcs-app/frontend/src/views/configuration/mesos-create/secret.vue, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue
=> fix: 修复tab滚动显示不全问题

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/apps/cluster/views_bk/node.py, bcs-app/backend/bcs_k8s/kubectl/kubectl.py
=> feat: update node delete api

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/components/data-searcher/index.vue, bcs-app/frontend/src/views/configuration/instantiation.vue, bcs-app/frontend/src/views/configuration/k8s-create/ingress.vue, bcs-app/frontend/src/views/configuration/mesos-create/configmap.vue, bcs-app/frontend/src/views/configuration/mesos-create/header.vue, bcs-app/frontend/src/views/configuration/namespace.vue
变更点(Changes)
- mesos configmap增加凭证 
- 修复整体列表默认集群维度
=> add: mesos configmap增加凭证 & 修复整体列表默认集群维度

bcs-app/frontend/src/views/configuration/namespace.vue
变更点(Changes)
fix: 修复命名空间集群获取问题
=> fix: 修复命名空间集群获取问题

bcs-app/frontend/src/views/configuration/namespace.vue, bcs-app/frontend/src/views/network/loadbalance/k8s/index.css, bcs-app/frontend/src/views/network/loadbalance/k8s/index.vue
变更点(Changes)
update: 同步k8s loadbalancer
=> update: 同步k8s loadbalancer

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue
=> fix: 修复模板集保存报问题

bcs-app/backend/apps/cluster/views/node.py, bcs-app/backend/apps/network/views/charts/releases.py, bcs-app/backend/apps/network/views/lb/k8s.py
变更点(Changes)
修复添加系统变量问题及操作节点的日志问题
=> fix: fix k8s lb system renderer and operate node desc

bcs-app/backend/apis/resources/node.py, bcs-app/backend/apis/resources/serializers.py, bcs-app/backend/apis/resources/urls.py, bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/operation_apis.py, bcs-app/backend/apps/cluster/views/node_views/query_apis.py, bcs-app/backend/apps/cluster/views/node_views/serializers.py, bcs-app/backend/components/bcs/mesos.py, bcs-app/backend/resources/cluster/utils.py
变更点(Changes)
更新mesos 节点label API
=> feat: update mesos node labels api

bcs-app/backend/components/cc.py
变更点(Changes)
更新查询cmdb接口，允许选择蓝鲸业务
=> feat: update cc biz api

bcs-projmgr/frontend/src/assets/static/env.js.tpl
=> 修改项目管理的文档中心地址。

bcs-app/backend/bcs_k8s/kubehelm/exceptions.py, bcs-app/backend/bcs_k8s/kubehelm/templates/inject_bcs_info.yaml
变更点(Changes)
- 更新helm异常返回消息
- 修复cronjob注入时的imagesecret追加
=> feat: update helm apis

bcs-app/frontend/build/webpack.dev.conf.js, bcs-app/frontend/build/webpack.prod.conf.js, bcs-app/frontend/index.html, bcs-app/frontend/package.json, bcs-app/frontend/src/App.vue, bcs-app/frontend/src/views/side-nav.vue
变更点(Changes)
update: 打包时，前端支持传递版本(企业版或社区版)参数，进行区别出版本
=> update: 打包时，前端支持传递版本(企业版或社区版)参数，进行区别出版本

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/index.vue, bcs-app/frontend/src/views/cluster/node.external.vue
=> perf: 导入集群操作调整

bcs-app/backend/apps/network/views/lb/constants.py, bcs-app/backend/apps/network/views/lb/constants_bk.py, bcs-app/backend/apps/network/views/lb/mesos_new.py, bcs-app/backend/settings/ce/base.py
=> feat: update mesos lb

bcs-app/backend/settings/ce/base.py, bcs-cc/confcenter/tasks/node.go, bcs-cc/storage/models/node.go
=> feat: update sync bcs node and configs

bcs-app/backend/apps/application/all_views/mesos_views.py, bcs-app/backend/apps/configuration/namespace/resources/k8s.py, bcs-app/backend/apps/configuration/namespace/serializers.py, bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/apps/constants.py, bcs-app/backend/apps/network/views/service.py, bcs-app/backend/apps/resource/views.py, bcs-app/backend/bcs_k8s/app/views.py, bcs-app/backend/resources/namespace/constants.py
变更点(Changes)
更新过滤命名空间和查询storage接口字段
=> feat: update filter ns and storage fileds

bcs-app/backend/apps/configuration/namespace/serializers.py, bcs-app/backend/apps/configuration/namespace/views.py, bcs-app/backend/bcs_k8s/app/views.py, bcs-app/backend/resources/namespace/constants.py
=> feat: skip plat and sys namespace

bcs-app/backend/resources/namespace/constants.py
=> feat: update filter ns

bcs-app/backend/apps/cluster/views_bk/configs/k8s.py, bcs-app/backend/bcs_k8s/app/deployer.py, bcs-app/backend/components/bcs/resources/replicaset.py
变更点(Changes)
更新查询k8s api功能，增加平台注入变量功能
=> feat: update k8s query api

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/operation_apis.py, bcs-app/backend/apps/cluster/views_bk/cluster.py, bcs-app/backend/apps/cluster/views_bk/configs/k8s.py
=> feat: support to delete failed cluster info

bcs-cc/confcenter/tasks/node.go
=> fix: get cluster state apis

bcs-app/backend/apps/network/views/lb/mesos_new.py
=> feat: update lb status

bcs-app/frontend/src/views/cluster/overview.vue
变更点(Changes)
update: 删除总览页面中的集群IP视图
=> update: 删除总览页面中的集群IP视图

bcs-app/frontend/src/views/cluster/overview.vue, bcs-app/frontend/src/views/helm/tpl-list.vue
变更点(Changes)
fix: 兼容helm chart版本字段为空情况
=> fix: 兼容helm chart版本字段为空情况

bcs-app/backend/apps/network/views/lb/utils.py
=> feat: fix mesos lb label index

bcs-app/frontend/index-dev.html.example, bcs-app/frontend/index.html, bcs-app/frontend/src/App.vue, bcs-app/frontend/src/views/side-nav.vue
变更点(Changes)
feat: 添加 SUPPORT_MESOS 用于判断开启容器服务时是否显示 BCS-Mesos 单选框
=> feat: 添加 SUPPORT_MESOS 用于判断开启容器服务时是否显示 BCS-Mesos 单选框

bcs-app/requirements.txt
=> feat: update bcs saas requirements

bcs-app/backend/apps/configuration/fixture/template_k8s.py, bcs-app/backend/apps/configuration/fixture/template_mesos.py, bcs-app/backend/apps/network/views/lb/utils.py
=> feat: update initial tmpl conf

bcs-app/backend/apps/cluster/urls.py, bcs-app/backend/apps/cluster/views/__init__.py, bcs-app/backend/apps/cluster/views/node_views/query_apis.py, bcs-app/backend/apps/cluster/views/node_views/utils.py, bcs-app/backend/resources/cluster/utils.py, bcs-app/backend/tests/nodes/test_utils.py, bcs-app/backend/tests/resources/cluster/test_utils.py
变更点(Changes)
更新查询mesos集群label的key val，用于前端过滤使用
=> feat: update mesos key-val of labels apis

bcs-app/backend/components/bcs/resources/api_response.py, bcs-app/backend/tests/resources/test_api_response.py, bcs-app/backend/tests/resources/test_resources.py, bcs-app/backend/tests/testing_utils/base.py, bcs-app/dev_utils/README.md, bcs-app/dev_utils/docker-compose.yaml
- 增加依赖 apiserver 的少量 resources 单元测试
- 重构 api_response.response 装饰器
- 修改 response 装饰器在出现普通 Exception 时，直接把异常放入 message
字段的问题
=> comp.resources 模块：补充少量单测 / 重构 response

bcs-app/.flake8, bcs-app/backend/resources/client.py, bcs-app/backend/tests/resources/conftest.py, bcs-app/backend/tests/resources/test_client.py, bcs-app/backend/tests/resources/test_resources.py
- 拆分用于生成访问 Kubernetes 集群的 Config 对象逻辑
- 补充配置生成单元测试
=> 拆分用于生成访问 Kubernetes 集群的 Config 对象逻辑 / 单元测试

bcs-app/backend/apis/templatesets/form_mode/deployer.py, bcs-app/backend/resources/cluster/__init__.py, bcs-app/backend/resources/cluster/constants.py, bcs-app/backend/resources/custom_object/__init__.py, bcs-app/backend/resources/custom_object/crd.py, bcs-app/backend/resources/custom_object/custom_object.py, bcs-app/backend/resources/custom_object/custom_objects_api.py, bcs-app/backend/resources/deployment/deployment.py, bcs-app/backend/resources/namespace/__init__.py, bcs-app/backend/resources/namespace/namespace.py, bcs-app/backend/resources/pod/__init__.py, bcs-app/backend/resources/pod/pod.py, bcs-app/backend/resources/project/utils.py, bcs-app/backend/utils/basic.py
变更点(Changes)
resources 模块新增Pod等资源
=> refactor: merge resources module

bcs-app/backend/apps/application/utils.py, bcs-app/backend/apps/network/views/lb/utils.py, bcs-app/backend/tests/app/application/test_utils.py
=> Fix resource status

bcs-app/backend/dashboard/custom_object/constants.py, bcs-app/backend/resources/constants.py, bcs-app/backend/resources/custom_object/constants.py, bcs-app/backend/resources/custom_object/custom_object.py
变更点(Changes)
开放GameDeployment自定义对象的支持
=> feat: add gamedeployment custom object

bcs-app/backend/resources/deployment/deployment.py, bcs-app/backend/resources/namespace/namespace_quota.py, bcs-app/backend/resources/pod/pod.py, bcs-app/backend/resources/utils/filters.py, bcs-app/backend/resources/utils/format.py, bcs-app/backend/resources/utils/kube_client.py, bcs-app/backend/tests/resources/conftest.py, bcs-app/backend/tests/resources/deployment/test_deployment.py, bcs-app/backend/tests/resources/namespace/test_namespace_quota.py, bcs-app/backend/tests/resources/pod/test_pod.py, bcs-app/backend/tests/resources/utils/test_filters.py, bcs-app/backend/tests/resources/utils/test_format.py, bcs-app/backend/tests/resources/utils/test_kube_client.py, bcs-app/backend/utils/basic.py
变更点(Changes)
重构部分 resources.Deployment 代码
=> 重构部分 resources.Deployment 代码

bcs-app/backend/apps/cluster/views/node_views/utils.py, bcs-app/backend/tests/nodes/test_utils.py
变更点(Changes)
修复mesos节点label为空时的异常问题
=> fix: 修复mesos节点label为空时的异常

bcs-app/backend/components/paas_cc.py, bcs-app/backend/tests/api/test_resource.py, bcs-app/backend/tests/bcs_mocks/data/paas_cc_json.py, bcs-app/backend/tests/bcs_mocks/misc.py, bcs-app/backend/tests/conftest.py, bcs-app/backend/tests/resources/conftest.py, bcs-app/backend/tests/resources/test_resources.py
变更点(Changes)
- 添加针对 ConfigMap.get 接口的 API 测试（DEMO 用）
- 增加 PaaSCC 等模块的 fake 实现
- 调整部分测试 fixture 位置
=> 添加针对 ConfigMap.get 接口的 API 测试

bcs-app/frontend/src/components/ring.vue, bcs-app/frontend/src/components/tip-dialog/index.vue, bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/list.css, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js, bcs-app/frontend/src/views/cluster/mixin-node.js
变更点(Changes)
fix: 【社区版】2021-01-06体验问题汇总
=> fix: 【社区版】2021-01-06体验问题汇总

bcs-app/frontend/src/components/bk-searcher/index.css, bcs-app/frontend/src/components/bk-searcher/index.vue, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
feat(app): 命名空间名称 filter 增加集群 id 的显示
=> feat(app): 命名空间名称 filter 增加集群 id 的显示

bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js
=> fix: 指标数据页面样式问题

bcs-app/frontend/src/views/app/list.css
变更点(Changes)
fix(app): 修复更多操作下拉框被挡住的问题
=> fix(app): 修复更多操作下拉框被挡住的问题

bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue, bcs-app/frontend/src/views/configuration/mesos-create/application.vue
变更点(Changes)
fix: 调整版本为变量时的镜像拼接规则
=> fix: 调整版本为变量时的镜像拼接规则

bcs-app/backend/bcs_k8s/app/models.py, bcs-app/backend/bcs_k8s/helm/constants.py, bcs-app/backend/bcs_k8s/helm/models/chart.py, bcs-app/backend/bcs_k8s/helm/models/repo.py
=> feat: support chart version from repo

bcs-app/backend/bcs_k8s/app/utils.py
变更点(Changes)
查询helm状态的dashboard升级后，返回的部分资源字段有变动；修复返回给前端字段不统一问题
=> fix: 修复查询helm资源状态返回字段问题

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/components/number/index.css, bcs-app/frontend/src/components/number/index.vue, bcs-app/frontend/src/components/ring.vue, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/list.css, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js, bcs-app/frontend/src/views/cluster/ring-cell.vue
=> fix: 修复体验问题

bcs-app/frontend/src/components/app-header.vue
变更点(Changes)
fix: 修复切换左侧菜单后，在顶导切换项目报错的问题
=> fix: 修复切换左侧菜单后，在顶导切换项目报错的问题

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
fix(app): 扩缩容弹框标题超长显示的问题
=> fix(app): 扩缩容弹框标题超长显示的问题

bcs-app/backend/settings/base.py
=> fix: 修复 dashboard 版本匹配

bcs-app/backend/bcs_k8s/helm/models/repo.py
=> fix: 更新获取repo的username和password

bcs-app/frontend/src/components/bk-input/index.vue, bcs-app/frontend/src/views/configuration/templateset.css, bcs-app/frontend/src/views/configuration/templateset.vue
变更点(Changes)
update: 模板集加载更多调整及bk-input问题修复
=> update: 模板集加载更多调整及bk-input问题修复

bcs-app/frontend/src/views/app/k8s-state.js
变更点(Changes)
fix(app): status 为 Running 时，不判断 instance 为 0 以及其他条件，所有操作均可用
=> fix(app): status 为 Running 时，不判断 instance 为 0 以及其他条件，所有操作均可用

bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
chore(app): 扩缩容实例数量由 build_instance 改为 instance
=> chore(app): 扩缩容实例数量由 build_instance 改为 instance

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
feat(cluster): Imported 国际化
=> feat(cluster): Imported 国际化

bcs-app/frontend/src/config.js
变更点(Changes)
update: 更新推送镜像文档地址
=> update: 更新推送镜像文档地址

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/node.external.vue
变更点(Changes)
自有集群添加节点按钮添加 tips
=> update: 自有集群添加节点按钮添加 tips

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/node.external.vue
变更点(Changes)
更新自有集群"添加节点"的按钮文案
=> refactor: update tips

bcs-app/frontend/src/components/bk-searcher/index.css, bcs-app/frontend/src/components/bk-searcher/index.vue, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/mesos/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js
变更点(Changes)
fix(app): 修复应用视图集群切换数据重叠的问题
=> fix(app): 修复应用视图集群切换数据重叠的问题

bcs-app/frontend/src/views/app/k8s/tmpl-list.html
变更点(Changes)
bugfix: 滚动升级 实例数 不允许变化
=> bugfix: 滚动升级 实例数 不允许变化

bcs-app/backend/infras/host_service/host.py, bcs-app/backend/tests/infras/host_service/test_host.py
变更点(Changes)
更新集群或节点获取cmdb host 功能
=> feat: 更新集群或节点获取cmdb host功能

bcs-app/backend/dashboard/custom_object/utils.py, bcs-app/backend/dashboard/custom_object/views.py, bcs-app/backend/tests/dashboard/custom_object/test_utils.py
变更点(Changes)
将cluster_id添加回crd的table_format
=> refactor: add cluster_id to crd table_format

bcs-app/backend/dashboard/custom_object/utils.py, bcs-app/backend/dashboard/custom_object/views.py, bcs-app/backend/resources/custom_object/constants.py, bcs-app/backend/resources/custom_object/crd.py, bcs-app/backend/resources/custom_object/custom_object.py
变更点(Changes)
修复：指定preferred=True时，custom object可能查找不到的问题
=> fix: CustomObject need api_version when preferredVersion not work

bcs-app/frontend/src/css/bk-patch.css
变更点(Changes)
fix(app): 操作按钮对齐问题
=> fix(app): 操作按钮对齐问题

bcs-app/frontend/src/views/app/k8s/tmpl-list.html
变更点(Changes)
fix(app): 变量按钮不允许使用
=> fix(app): 变量按钮不允许使用

bcs-app/backend/resources/custom_object/custom_object.py
变更点(Changes)
修复_get_cobj_api_version处理apiextensions.k8s.io/v1beta1可能不指定versions的问题
=> fix: func _get_cobj_api_version

bcs-app/requirements.txt
变更点(Changes)
出于安全问题，从requirements.txt移除bk-iam包
=> chore: delete bk-iam from requirements.txt

bcs-app/backend/bcs_k8s/app/views.py, bcs-app/backend/bcs_k8s/helm/providers/constants.py, bcs-app/backend/celery_app/__init__.py, bcs-app/backend/components/ticket.py, bcs-app/backend/settings/base.py, bcs-app/backend/settings/ce/base.py, bcs-app/backend/utils/exceptions_bk.py, bcs-app/backend/web_console/constant_bk.py, bcs-app/backend/web_console/rest_api/views_bk.py
版本合并调整：
- backend.bcs_k8s, constants and bcs-agent YAML
- celery_app
=> 版本合并：backend.bcs_k8s.constants and bcs-agent YAML / celery_app.__init__

bcs-app/backend/apps/hpa/utils.py, bcs-app/backend/apps/hpa/views.py, bcs-app/backend/apps/instance/drivers/k8s.py, bcs-app/backend/resources/hpa/exceptions.py, bcs-app/backend/resources/hpa/format.py, bcs-app/backend/resources/hpa/hpa.py, bcs-app/backend/resources/resource.py, bcs-app/backend/tests/conftest.py, bcs-app/backend/tests/resources/hpa/sample_cpu_hpa.yaml, bcs-app/backend/tests/resources/hpa/test_hpa.py
- k8s hpa client 替换为 dynamic client
- mesos保持不变
=> k8s hpa use dynamic client

bcs-app/backend/dashboard/custom_object/serializers.py, bcs-app/backend/dashboard/custom_object/urls.py, bcs-app/backend/dashboard/custom_object/views.py
变更点(Changes)
支持批量删除custom object
=> feat: support batch delete custom object

bcs-app/Makefile, bcs-app/poetry.lock, bcs-app/pyproject.toml
变更点(Changes)
- 使用 poetry 管理项目依赖包（未变更当前 requiments.txt）
=> Add poetry dependencies config file

bcs-app/frontend/src/views/cluster/searcher/index.vue
变更点(Changes)
update: searcher 组件接口适配 mesos
=> update: searcher 组件接口适配 mesos

bcs-app/backend/bcs_k8s/kubehelm/helm.py, bcs-app/backend/tests/helm/test_kube_helm_client.py
变更点(Changes)
helm命令支持--reuse-values参数
=> feat: helm添加支持--reuse-values命令

bcs-app/frontend/src/views/cluster/searcher/index.vue
=> update: paste 事件过滤\r

bcs-app/backend/components/cc.py, docs/release.md
变更点(Changes)
更新查询cmdb业务下主机信息接口
=> Update cmdb search host

bcs-app/backend/apps/cluster/serializers.py, bcs-app/backend/apps/projects/views.py, bcs-app/backend/bcs_k8s/app/repo.py, bcs-app/backend/bcs_k8s/app/utils.py, bcs-app/backend/components/cc.py
=> fix: 修复合并代码是的异常问题

bcs-app/backend/bcs_k8s/kubehelm/exceptions.py, bcs-app/backend/bcs_k8s/kubehelm/helm.py, bcs-app/backend/bcs_k8s/kubehelm/options.py, bcs-app/backend/tests/helm/test_kube_helm_client.py, bcs-app/backend/tests/helm/test_options.py
变更点(Changes)
支持有序的helm options
=> feat: add Class Options to support helm ordered options

bcs-app/backend/apps/cluster/constants.py, bcs-app/backend/apps/cluster/driver/mesos.py
变更点(Changes)
针对mesos忽略bcs-system命名空间下的资源
=> feat: 针对mesos忽略bcs-system命名空间下的资源

docs/release.md
=> docs: update release.md

bcs-app/frontend/src/views/metric/index.vue
=> feat: metric 管理

bcs-app/backend/accounts/bcs_perm/__init__.py, bcs-app/backend/apps/cluster/views/cluster.py, bcs-app/backend/apps/projects/views.py, bcs-app/backend/settings/ce/base.py
变更点(Changes)
添加ServiceMonitor code到DIRECT_ON_FUNC_CODE
=> feat: add ServiceMonitor in DIRECT_ON_FUNC_CODE

bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/app/views.py
变更点(Changes)
release列表接口返回chart名称
=> feat: return chart name

bcs-app/frontend/src/views/helm/app-detail.vue, bcs-app/frontend/src/views/helm/tpl-instance.vue
=> feat: helm 参数更新

bcs-app/backend/apis/views.py, bcs-app/backend/apps/application/base_views.py, bcs-app/backend/apps/application/instance_views.py, bcs-app/backend/apps/cluster/flow_views/cluster.py, bcs-app/backend/apps/cluster/flow_views/node.py, bcs-app/backend/apps/depot/api.py, bcs-app/backend/components/enterprise/bk_login.py, bcs-app/backend/components/enterprise/cmsi.py, bcs-app/backend/tests/utils/test_error_codes.py, bcs-app/backend/utils/error_codes.py, bcs-app/backend/utils/views.py
修改错误代码实现，使用 blue_krill.web.std_error 模块
=> 修改错误代码实现，使用 blue_krill.web.std_error 模块

bcs-app/backend/apps/cluster/driver/mesos.py, bcs-app/backend/apps/cluster/views/cluster.py, bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/app/views.py, bcs-app/backend/settings/ce/base.py, bcs-app/backend/tests/apps/cluster/mesos/containers.py, bcs-app/backend/tests/bcs_k8s/app/utils.py
=> bugfix: fix skip namespace and compare time

bcs-app/backend/apps/cluster/tasks.py, bcs-app/backend/bcs_k8s/app/views.py
=> bugfix: fix bugs

bcs-app/backend/apps/cluster/constants.py, bcs-app/backend/apps/cluster/driver/mesos.py
变更点(Changes)
mesos过滤bcs system命名空间
=> feat: ignore bcs system namespace for mesos

bcs-app/frontend/src/common/util.js, bcs-app/frontend/src/views/configuration/mesos-create/header.vue, bcs-app/frontend/src/views/configuration/templateset.vue
变更点(Changes)
feat: 优化Mesos导入导出模板集逻辑
=> feature: Mesos导入导出功能优化

bcs-app/frontend/src/common/util.js
变更点(Changes)
minor：eslint空格问题导致构建失败
=> minor: eslint格式修改

bcs-app/frontend/src/common/util.js, bcs-app/frontend/src/views/configuration/mesos-create/header.vue, bcs-app/frontend/src/views/configuration/templateset.vue
=> feat: Mesos模板集导入导出功能优化

bcs-app/backend/resources/utils/kube_client.py
变更点(Changes)
update_or_create中，replace操作增加设置metadata.resourceVersion逻辑
=> fix: metadata.resourceVersion must be specified for an update

bcs-app/backend/apps/cluster/views/cluster.py
=> feat: 展示cidr

bcs-app/backend/apps/hosts/serializers.py, bcs-app/backend/infras/host_service/host.py, bcs-app/backend/tests/infras/host_service/test_host.py
=> feat: 支持vpc name

bcs-app/backend/bcs_k8s/helm/serializers.py, bcs-app/backend/urls.py, bcs-app/backend/utils/serializers.py
- fix:  serializers.DateTimeField(default_timezone=settings.TIME_ZONE) ，这个写法已经过时，default_timezone需要是一个tz对象
- drf已经能正常返回当前时区数据，不需要patch了
=> fix timezone error

bcs-app/backend/apis/views.py
变更点(Changes)
import correct get_access_token
=> fix: import correct get_access_token

bcs-app/backend/bcs_k8s/app/serializers.py, bcs-app/backend/bcs_k8s/helm/views.py, bcs-app/backend/utils/views.py
变更点(Changes)
更新helm backend api
=> feat: update helm backend api

bcs-app/backend/packages/blue_krill/data_types/enum.py
变更点(Changes)
给StructuredEnum新增get_values和get_labels方法
=> feat: add get_values and get_labels class method for StructuredEnum

bcs-app/backend/apps/network/urls.py, bcs-app/backend/apps/network/views/lb/mesos_new.py
变更点(Changes)
action不允许使用`detail`关键字
=> bugfix: fix url action

bcs-app/backend/tests/resources/formatter/conftest.py, bcs-app/backend/tests/resources/formatter/networks/test_endpoints.py, bcs-app/backend/tests/resources/formatter/networks/test_ingress.py, bcs-app/backend/tests/resources/formatter/networks/test_service.py, bcs-app/backend/tests/resources/formatter/storages/test_persistent_volume.py, bcs-app/backend/tests/resources/formatter/storages/test_persistent_volume_claim.py, bcs-app/backend/tests/resources/formatter/storages/test_storage_class.py, bcs-app/backend/tests/resources/formatter/workloads/test_cronjob.py, bcs-app/backend/tests/resources/formatter/workloads/test_daemonset.py, bcs-app/backend/tests/resources/formatter/workloads/test_deployment.py, bcs-app/backend/tests/resources/formatter/workloads/test_job.py, bcs-app/backend/tests/resources/formatter/workloads/test_pod.py, bcs-app/backend/tests/resources/formatter/workloads/test_statefulset.py
变更点(Changes)
fomatter unittest's json file path use absolute path.
=> minor: fix json file path.

bcs-app/backend/celery_app/__init__.py, docs/release.md
=> bugfix: fix import tasks

bcs-app/backend/celery_app/__init__.py, docs/release.md
=> Fix import tasks

bcs-app/backend/apps/network/ext_routes.py, bcs-app/backend/apps/network/views/service.py
变更点(Changes)
由于功能调整，get_svc_extended_routes必须传入cluster_id
=> fix: add cluster_id in func get_svc_extended_routes

bcs-app/backend/utils/async_run.py
变更点(Changes)
如果获取到的event loop已经关闭，则重新创建新的
=> fix: recreate event_loop when old loop is closed

bcs-app/backend/resources/workloads/cronjob/formatter.py, bcs-app/backend/resources/workloads/pod/utils.py, bcs-app/backend/tests/resources/utils/contents/pod_configs.py, bcs-app/backend/tests/resources/utils/test_pod_status_parser.py, bcs-app/backend/utils/basic.py
=> bugfix: fix some field value.

bcs-app/backend/settings/ce/base.py
=> Add mesos resource wlist

bcs-app/backend/resources/pod/log.py, bcs-app/backend/resources/utils/kube_client.py
变更点(Changes)
增加wrap_kube_client_exc包装dynamic client的异常
=> feat: add wrap_kube_client_exc to wrap dynamic client exception

bcs-app/backend/apis/urls.py, bcs-app/backend/apis/variables/urls.py, bcs-app/backend/apis/variables/var_helper.py, bcs-app/backend/apis/variables/views.py, bcs-app/backend/components/paas_cc.py, bcs-app/backend/tests/api/test_resource.py, bcs-app/backend/tests/api/variables/test_var_helper.py, bcs-app/backend/tests/api/variables/test_views.py, bcs-app/backend/tests/bcs_mocks/misc.py
=> Support namespace vars api

bcs-app/frontend/src/views/cluster/index.vue, bcs-app/frontend/src/views/cluster/status-progress.vue
变更点(Changes)
fix: mesos cluster metrics/overview 请求
=> fix: mesos cluster metrics/overview 请求

bcs-app/frontend/src/views/cluster/index.vue, bcs-app/frontend/src/views/cluster/status-progress.vue
变更点(Changes)
fix: mesos cluster metrics/overview 请求
=> Release 1.4.3

bcs-app/frontend/src/views/cluster/searcher/index.vue
变更点(Changes)
节点标签列表接口兼容
Fixes #
=> fix: 节点标签列表接口兼容

bcs-app/backend/apps/cluster/flow_views/tools/gse/__init__.py, bcs-app/backend/apps/cluster/views/node.py, docs/release.md
变更点(Changes)
修复由于cmdb获取主机列表接口返回字段变动导致的问题
=> Fix cmdb bk cloud ids type

bcs-app/backend/container_service/projects/views.py
=> refactor: relocate modules

bcs-app/backend/web_console/rest_api/views.py
=> Relocate modules

bcs-app/Makefile, bcs-app/backend/accounts/middlewares.py, bcs-app/requirements.txt
变更点(Changes)
从requirements.txt中移除twisted-iocpsupport和colorama
=> chore: uninstall twisted-iocpsupport and colorama

bcs-app/backend/tests/helm/releases/conftest.py
变更点(Changes)
修复relocate-modules
=> fix: relocate-modules

bcs-app/backend/utils/async_run.py
变更点(Changes)
async_run函数支持返回结果
=> feat: refactor func async_run to return result

bcs-app/backend/apis/projects/urls.py, bcs-app/backend/apps/projects/serializers.py, bcs-app/backend/apps/projects/views.py, bcs-app/backend/components/iam/permissions.py, bcs-app/backend/utils/async_run.py
=> feat: support batch verify user project perms api

bcs-app/backend/container_service/infras/hosts/terraform/views.py, bcs-app/backend/container_service/projects/cmdb.py, bcs-app/backend/container_service/projects/urls.py, bcs-app/backend/container_service/projects/views.py, bcs-app/backend/tests/container_service/projects/test_cmdb.py
=> feat: restrict maintainer role

bcs-app/backend/bcs_web/constants.py, bcs-app/backend/bcs_web/permissions.py, bcs-app/backend/container_service/projects/views.py
变更点(Changes)
修复更新项目时，缓存key不正确问题
=> fix: fix project cache key

bcs-app/frontend/src/views/configuration/k8s-create/header.vue
变更点(Changes)
修复 service 切换的时候不自动保存数据
=> fix: service 切换的时候自动保存数据

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/dashboard/configuration/config-maps-detail.vue, bcs-app/frontend/src/views/dashboard/configuration/config-maps.vue, bcs-app/frontend/src/views/dashboard/configuration/secrets-detail.vue, bcs-app/frontend/src/views/dashboard/configuration/secrets.vue, bcs-app/frontend/src/views/dashboard/rbac/service-accounts-detail.vue, bcs-app/frontend/src/views/dashboard/rbac/service-accounts.vue
=> feat: 配置|RBAC 详情页开发

bcs-app/frontend/src/views/dashboard/common/status-icon.css, bcs-app/frontend/src/views/dashboard/common/status-icon.tsx, bcs-app/frontend/src/views/dashboard/workload/detail/container-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/detail-basic.ts, bcs-app/frontend/src/views/dashboard/workload/detail/detail-info.css, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
=> feat: 资源视图详情开发

bcs-app/frontend/src/views/dashboard/workload/detail/detail-info.css, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/use-detail.ts, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
=> refactor: 提取公共代码

bcs-app/frontend/src/components/bk-input/combox.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue
变更点(Changes)
fix: 修复模板集加载其他版本时镜像版本控件不回填问题
Fixes #
=> fix: 修复模板集加载其他版本时镜像版本控件不回填问题

bcs-app/frontend/src/store/index.js, bcs-app/frontend/src/views/dashboard/common/metric.vue, bcs-app/frontend/src/views/dashboard/workload/detail/detail-top-nav.vue, bcs-app/frontend/src/views/dashboard/workload/detail/index.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue, bcs-app/frontend/src/views/side-nav.vue
变更点(Changes)
optimization: 资源视图图表空状态优化和详情路由刷新问题
Fixes #
=> optimization: 资源视图图表空状态优化和详情路由刷新问题

bcs-app/frontend/src/@types/index.d.ts, bcs-app/frontend/src/views/dashboard/common/default-echarts-option.ts, bcs-app/frontend/src/views/dashboard/common/status-icon.tsx, bcs-app/frontend/src/views/dashboard/configuration/config-maps-detail.vue, bcs-app/frontend/src/views/dashboard/namespace.tsx, bcs-app/frontend/src/views/dashboard/network/ingress-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/container-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/detail-basic.ts, bcs-app/frontend/src/views/dashboard/workload/detail/detail-info.css, bcs-app/frontend/src/views/dashboard/workload/detail/detail-top-nav.vue, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/use-detail.ts, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue, bcs-app/frontend/src/views/dashboard/workload/pods.vue
变更点(Changes)
optimization: 优化详情代码
Fixes #
=> optimization: 优化详情代码

bcs-app/frontend/src/views/dashboard/configuration/config-maps-detail.vue, bcs-app/frontend/src/views/dashboard/configuration/secrets-detail.vue, bcs-app/frontend/src/views/dashboard/rbac/service-accounts-detail.vue
=> fix: table直接赋值对象报错问题

bcs-app/frontend/src/views/dashboard/workload/detail/detail-basic.ts, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
变更点(Changes)
fix: 详情默认值修改
Fixes #
=> fix: 详情默认值修改

bcs-app/frontend/src/views/dashboard/workload/cronjobs.vue, bcs-app/frontend/src/views/dashboard/workload/daemonsets.vue, bcs-app/frontend/src/views/dashboard/workload/deployments.vue, bcs-app/frontend/src/views/dashboard/workload/detail/index.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue, bcs-app/frontend/src/views/dashboard/workload/jobs.vue, bcs-app/frontend/src/views/dashboard/workload/pods.vue, bcs-app/frontend/src/views/dashboard/workload/statefulsets.vue
变更点(Changes)
fix: 详情界面在内容过长是出现滚动条问题
Fixes #
=> fix: 详情界面在内容过长是出现滚动条问题

bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/workload/cronjobs.vue, bcs-app/frontend/src/views/dashboard/workload/daemonsets.vue, bcs-app/frontend/src/views/dashboard/workload/deployments.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue, bcs-app/frontend/src/views/dashboard/workload/jobs.vue, bcs-app/frontend/src/views/dashboard/workload/pods.vue, bcs-app/frontend/src/views/dashboard/workload/statefulsets.vue
变更点(Changes)
fix: 优化资源视图反馈问题
Fixes #
=> fix: 优化资源视图反馈问题

bcs-app/frontend/.gitignore
变更点(Changes)
minor: gitignore修改
Fixes #
=> minor: gitignore修改

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/create.vue
变更点(Changes)
update: 新增集群添加节点提示
=> update: 新增集群添加节点提示

bcs-app/frontend/src/components/cluster-selector/index.vue, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/configuration/config-maps-detail.vue, bcs-app/frontend/src/views/dashboard/configuration/secrets-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
变更点(Changes)
fix: 资源视图体验问题修复相关issues (Which issues this PR fixes)
Fixes #
=> fix: 资源视图体验问题修复

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/create.vue
=> chore: 调整大小写

bcs-app/frontend/src/store/menu-config.js
变更点(Changes)
optimization: 存储和配置菜单位置调整
Fixes #
=> optimization: 存储和配置菜单位置调整

bcs-app/frontend/src/store/menu-config.js, bcs-app/frontend/src/views/dashboard/common/use-cluster.ts
变更点(Changes)
fix: 修复资源视图集群显示问题
Fixes #
=> fix: 修复资源视图集群显示问题

bcs-app/frontend/src/views/dashboard/common/use-cluster.ts
变更点(Changes)
fix: 修复视图切花集群显示问题
Fixes #
=> fix: 修复视图切花集群显示问题

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/dashboard/common/metric.vue
变更点(Changes)
fix: 集群接口重复发请求问题
Fixes #
=> fix: 集群接口重复发请求问题

bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
fix: 修复mesos集群显示报错问题
Fixes #
=> fix: 修复mesos集群显示报错问题

bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/index.vue, bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
fix: 修复代码问题
Fixes #
=> fix: 修复代码问题

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/views/configuration/namespace.vue
变更点(Changes)
fix: 修复进入命名空间后会延迟刷新界面
fix: 修复集群列表获取不正确
=> fix: 修复进入命名空间后会延迟刷新界面 && 修复集群列表获取不正确

bcs-app/frontend/src/App.vue
变更点(Changes)
fix: 集群列表接口获取问题
Fixes #
=> fix: 集群列表接口获取问题

bcs-app/frontend/src/views/cluster/mixin-node.js
变更点(Changes)
fix: 修复在集群概览节点tab页切换回全部集群是报错问题
Fixes #
=> fix: 修复在集群概览节点tab页切换回全部集群是报错问题

bcs-app/frontend/src/views/dashboard/common/status-icon.css
变更点(Changes)
fix: 修复集群概览页未初始化集群样式不对问题
Fixes #
=> fix: 修复集群概览页未初始化集群样式不对问题

bcs-app/backend/container_service/clusters/constants.py, bcs-app/backend/container_service/clusters/views/cluster.py
变更点(Changes)
返回集群使用的kube proxy
=> feat: return kube proxy for cluster

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx
变更点(Changes)
fix: 修复集群列表接口和feature_flags接口不能在未开启容器服务时调用问题
Fixes #
=> fix: 修复集群列表接口和feature_flags接口不能在未开启容器服务时调用问题

bcs-app/frontend/src/views/cluster/mixin-node.js
=> fix: 修复节点跨页全选问题

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/router/index.js, bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx
变更点(Changes)
fix: 修复切换单集群再切换项目时集群菜单未渲染问题
Fixes #
=> fix: 修复切换单集群再切换项目时集群菜单未渲染问题

bcs-app/frontend/src/router/index.js
变更点(Changes)
minor: 还原路由判断逻辑
Fixes #
=> minor: 还原路由判断逻辑

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/components/app-header.vue, bcs-app/frontend/src/router/dashboard.js
变更点(Changes)
update: 切换项目路由跳转到首页
update: dashboard 路由添加clusterId
update: 切换集群不需要刷新 router-view key
=> update: 优化项目交互

bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/workload/detail/index.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
变更点(Changes)
optimization: 获取工作负载下pod列表时新增owner_kind和owner_name参数
Fixes #
=> optimization: 获取工作负载下pod列表时新增owner_kind和owner_name参数

bcs-app/frontend/src/api/base.js, bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/modules/app.js, bcs-app/frontend/src/views/app/mesos/tmpl-list.html, bcs-app/frontend/src/views/app/mixins/mixin-base-list.mesos.js, bcs-app/frontend/src/views/cluster/info.vue
变更点(Changes)
update: mesos 添加原地资源扩容
update: 展示 kube-prooxy
=> update: mesos 添加原地资源扩容 && 展示 kube-prooxy

bcs-app/backend/bcs_web/audit_log/audit/context.py, bcs-app/backend/templatesets/legacy_apps/configuration/instance/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/views.py, bcs-app/backend/templatesets/var_mgmt/views.py
变更点(Changes)
利用property解决AuditContext类中extra的dict类型转换问题
=> refactor: change extra of AuditContext to property

bcs-app/backend/templatesets/legacy_apps/configuration/utils.py
=> fix: audit save serializer.data

bcs-app/frontend/src/components/app-header.vue, bcs-app/frontend/src/mixins/global.js, bcs-app/frontend/src/views/app/index.vue, bcs-app/frontend/src/views/app/mixins/mixin-base-instantiation.js, bcs-app/frontend/src/views/app/mixins/mixin-base-list.js, bcs-app/frontend/src/views/configuration/instantiation.vue, bcs-app/frontend/src/views/configuration/namespace.vue, bcs-app/frontend/src/views/crdcontroller/index.vue, bcs-app/frontend/src/views/mc/event-query.vue, bcs-app/frontend/src/views/network/service/mesos.vue, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue, bcs-app/frontend/src/views/storage/pv.vue
变更点(Changes)
fix: 切换项目导致参数丢失
optimization: curProjectCode, curProjectId, curClusterId 统一从store中获取
=> fix: 切换项目导致参数丢失 && optimization: curProjectCode, curProjectId, curClusterId 统一从store中获取

bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
update: 切换集群重新拉取数据
=> update: 切换集群重新拉取数据

bcs-app/frontend/static/ce.config.js
变更点(Changes)
minor: ce版本配置文件
Fixes #
=> minor: ce版本配置文件

bcs-app/frontend/src/views/app/mesos/tmpl-list.html
变更点(Changes)
MESOS应用页面展示调整
Fixes #
=> feat: MESOS应用页面展示调整

bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
fix: 修复离开界面轮询没有被清除
=> fix: 修复离开界面轮询没有被清除

bcs-app/backend/uniapps/application/all_views/mesos_views.py
变更点(Changes)
修复非平台滚动升级deployment时，其下application出现中间态，导致名称可能不一致的问题
=> bugfix: fix mesos deployment match name

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/components/cluster-selector/index.vue, bcs-app/frontend/src/views/side-nav.vue
变更点(Changes)
fix: 集群创建鉴权逻辑触发时机改为点击按钮触发 & 切换资源视图后在切回集群管理时项目Kind为空问题
Fixes #
=> fix: 集群创建鉴权逻辑触发时机改为点击按钮触发 & 切换资源视图后在切回集群管理时项目Kind为空问题

bcs-app/frontend/src/components/node-selector/index.vue
=> LoadBalancer选中机器节点bug修复

bcs-app/frontend/src/api/index.js, bcs-app/frontend/src/views/cluster/info.vue, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.vue, bcs-app/frontend/src/views/cluster/overview.vue
变更点(Changes)
optimization: 单集群概览页权限展示优化
Fixes #
=> optimization: 单集群概览页权限展示优化

bcs-app/frontend/src/views/node/index.css, bcs-app/frontend/src/views/node/index.vue, bcs-app/frontend/src/views/node/taint.vue
=> chore: 样式调整

bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
update: mesos 隐藏设置污点
Fixes #
=> update: mesos 隐藏设置污点

bcs-app/backend/resources/namespace/namespace_quota.py
变更点(Changes)
namespace qutoa中的ResourceField转换成dict
=> fix: transform resourcefield to dict

bcs-app/frontend/src/views/cluster/apply-host.vue
变更点(Changes)
bugfix: 修复申请主机参数显示错误
=> bugfix: 修复申请主机参数显示错误

bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue
变更点(Changes)
optimization: 更新功能交互优化
Fixes #
=> optimization: 更新功能交互优化

bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue
变更点(Changes)
optimization: 重置二次确认
Fixes #
=> optimization: 重置二次确认

bcs-app/frontend/src/views/cluster/apply-host.vue, bcs-app/frontend/src/views/node/index.css, bcs-app/frontend/src/views/node/index.vue, bcs-app/frontend/src/views/node/taint.vue
=> update: 节点样式交互调整

bcs-app/frontend/src/api/base.js
变更点(Changes)
minor: merge冲突问题
Fixes #
=> minor: merge冲突问题

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/api/base.js, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/storage/persistent-volumes-claims.vue, bcs-app/frontend/src/views/dashboard/storage/persistent-volumes.vue, bcs-app/frontend/src/views/dashboard/storage/storage-class.vue
变更点(Changes)
fix: 隐藏存储模块操作功能
Fixes #
=> fix: 隐藏存储模块操作功能

bcs-app/frontend/src/store/index.js, bcs-app/frontend/src/store/menu-config.js, bcs-app/frontend/src/views/dashboard/common/base-layout.css, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx
变更点(Changes)
fix: 修复样式覆盖问题
Fixes #
=> fix: 修复样式覆盖问题

bcs-app/frontend/src/App.vue
变更点(Changes)
fix: 修复loading遮挡未申请容器服务界面问题
Fixes #
=> fix: 修复loading遮挡未申请容器服务界面问题

bcs-app/frontend/src/store/modules/cluster.js, bcs-app/frontend/src/views/cluster/index.vue
变更点(Changes)
fix: 修复全部集群在非正常状态下未轮询问题 & 修复轮询时界面不断切换到创建容器服务界面问题
Fixes #
=> fix: 修复全部集群在非正常状态下未轮询问题 & 修复轮询时界面不断切换到创建容器服务界面问题

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue, bcs-app/frontend/src/views/dashboard/workload/detail/detail-info.css, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/use-detail.ts, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
=> update: 资源视图优化

bcs-app/backend/resources/resource.py, bcs-app/backend/resources/utils/discovery.py, bcs-app/backend/resources/utils/kube_client.py
变更点(Changes)
支持缓存dynamic client resource
=> feat: cache dynamic client resource

bcs-app/backend/settings/base.py
变更点(Changes)
删除settings中cmdb域名的多余配置
=> feat: delete bk cmdb config from settings

bcs-app/frontend/src/views/cluster/searcher/index.vue, bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue, bcs-app/frontend/src/views/node/index.vue
变更点(Changes)
bugfix: 修复 k8s 节点界面标签搜索问题
=> bugfix: 修复 k8s 节点界面标签搜索问题

bcs-app/frontend/src/components/bcs-unregistry/unregistry.vue
变更点(Changes)
minor: 文案优化
Fixes #
=> minor: 文案优化

bcs-app/backend/resources/namespace/namespace_quota.py, bcs-app/backend/utils/renderers.py
变更点(Changes)
当obj并非真正dataclass时，asdict抛出异常的问题
=> fix: asdict raise Exception when obj is not real dataclass type

bcs-app/frontend/src/views/crdcontroller/log_list.vue
变更点(Changes)
fix: 修复日志采集新建\编辑checkbox异常
=> fix: 修复日志采集新建\编辑checkbox异常

bcs-app/frontend/src/views/cluster/node.css, bcs-app/frontend/src/views/helm/tpl-detail.vue
1. 节点管理页面搜索框自适应宽度调整
2. Helm Chart的readme内容渲染展示
=> 节点管理页面搜索框自适应宽度调整 && Helm Chart的readme内容渲染展示

bcs-app/frontend/src/views/helm/app-detail.vue
Release更新页 helm部署选项timeout数据回填问题修复
=> fix: Release更新页 helm部署选项timeout数据回填问题修复

bcs-app/frontend/src/api/request.js, bcs-app/frontend/src/store/modules/dashboard.js, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/dashboard/common/use-table-data.ts, bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue, bcs-app/frontend/src/views/dashboard/workload/detail/use-detail.ts
变更点(Changes)
fix: 修改权限数据合并到data里面导致有些数据不可用问题
Fixes #
=> fix: 修改权限数据合并到data里面导致有些数据不可用问题

bcs-app/frontend/src/views/helm/app-detail.vue, bcs-app/frontend/src/views/helm/tpl-instance.vue
=> feat: HELM部署选项优化记录 

bcs-app/frontend/src/views/crdcontroller/index.vue
变更点(Changes)
fix: 修复组件库重新启用value_content内容不对问题
Fixes #
=> fix: 修复组件库重新启用value_content内容不对问题

bcs-app/backend/components/bcs/k8s_client.py, bcs-app/backend/tests/conftest.py
=> feat: add cluster cache

bcs-app/frontend/src/views/app/k8s/customobjects.vue, bcs-app/frontend/src/views/crdcontroller/index.vue
变更点(Changes)
optimization: 组件库文案优化和customobject样式调整
Fixes #
=> optimization: 组件库文案优化和customobject样式调整

bcs-app/backend/helm/app/documentation/how-to-push-chart.md, bcs-app/backend/helm/app/serializers.py
变更点(Changes)
当检测到重复key时，提示给用户相应的错误消息
=> feat: update values duplicate keys

bcs-app/frontend/src/api/index.js, bcs-app/frontend/src/views/app/k8s/tmpl-list.html, bcs-app/frontend/src/views/app/list.css
变更点(Changes)
optimization: 隐藏取消升级按钮 & 错误弹窗新增request_id内容
Fixes #
=> optimization: 隐藏取消升级按钮 & 错误弹窗新增request_id内容

bcs-app/frontend/src/components/bcs-md/index.vue, bcs-app/frontend/src/views/dashboard/resource-update/resource-update.vue
变更点(Changes)
fix: 修复md创建的时候value没有watch问题 & 背景色调整
Fixes #
=> fix: 修复md创建的时候value没有watch问题 & 背景色调整

bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/directives/full-screen.js, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx, bcs-app/frontend/src/views/helm/guide.vue
变更点(Changes)
optimization: helm md组件外部链接从新窗口打开 & 资源视图yaml新增复制和全屏功能
Fixes #
=> optimization: helm md组件外部链接从新窗口打开 & 资源视图yaml新增复制和全屏功能

bcs-app/frontend/src/views/configuration/k8s-create/yaml-mode/index.vue
变更点(Changes)
fix: 修复yaml模式表单模板集在选择节点然后导入不规范yaml时内容缓存问题
Fixes #
=> fix: 修复yaml模式表单模板集在选择节点然后导入不规范yaml时内容缓存问题

bcs-app/backend/tests/resources/node/test_node.py
=> bufix: fix node taint test

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/components/bcs-unregistry/unregistry.vue, bcs-app/frontend/src/views/helm/index.css, bcs-app/frontend/src/views/helm/index.vue, bcs-app/frontend/src/views/side-nav.vue
变更点(Changes)
fix: 私有化版本未开启容器服务界面没有获取CMDB业务的问题 & helm操作菜单下拉样式调整
Fixes #
=> fix: 私有化版本未开启容器服务界面没有获取CMDB业务的问题 & helm操作菜单下拉样式调整

bcs-app/frontend/src/views/configuration/namespace.vue
feat: 命名空间配额加载时，增加等待效果 issue #1251
=> feat: 命名空间配额加载时，增加等待效果 issue #1251

bcs-app/backend/components/cc.py, bcs-app/backend/tests/components/test_bk_cc.py, bcs-app/backend/tests/testing_utils/mocks/bk_cc.py
=> feat: add bk cc api

bcs-app/backend/helm/helm/views.py
=> minor: add query chart cost log

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/cluster/create.external.vue, bcs-app/frontend/src/views/helm/index.css, bcs-app/frontend/src/views/helm/index.vue, bcs-app/frontend/src/views/node/index.vue
节点ip精准搜索  #1268
helm release列表页优化  #1265
创建集群选择1个节点后，前端统计还是未选择节点(修复)
=> helm release列表页优化

bcs-app/backend/container_service/clusters/featureflag/constants.py, bcs-app/backend/container_service/clusters/featureflag/featflag.py, bcs-app/backend/container_service/clusters/featureflag/serializers.py, bcs-app/backend/dashboard/serializers.py, bcs-app/backend/dashboard/subscribe/serializers.py, bcs-app/backend/resources/custom_object/formatter.py, bcs-app/backend/tests/container_service/clusters/test_featureflag.py, bcs-app/frontend/src/views/helm/index.css, bcs-app/frontend/src/views/helm/index.vue
=> Helm Release列表调整

bcs-app/backend/container_service/projects/views.py, bcs-app/backend/helm/helm/models/managers.py, bcs-app/backend/helm/helm/serializers.py, bcs-app/backend/helm/helm/urls.py, bcs-app/backend/helm/helm/utils/chart.py, bcs-app/backend/helm/helm/views.py, bcs-app/backend/helm/open_apis/views.py, bcs-app/backend/tests/helm/helm/utils/test_chart.py
=> Update api performance

bcs-app/frontend/src/css/bk-patch.css, bcs-app/frontend/src/views/cluster/create.external.vue, bcs-app/frontend/src/views/helm/index.css, bcs-app/frontend/src/views/helm/index.vue, bcs-app/frontend/src/views/node/index.vue
1. 节点ip精准搜索 #1268
2.  helm release列表页优化  #1265
3. 创建集群选择1个节点后，前端统计还是未选择节点(修复)
=> 节点ip精准搜索 |  helm release列表页优化 

bcs-app/frontend/src/views/helm/index.css, bcs-app/frontend/src/views/helm/index.vue
变更点(Changes)
optimization: 优化表格宽度
Fixes #
=> optimization: 优化表格宽度

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/cluster/apply-host.vue
feat: 申请主机功能优化|放 开underly类型选择|前端支持
=> 申请主机功能优化|放 开underly类型选择|前端支持

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/store/menu-config.js, bcs-app/frontend/src/views/dashboard/storage/persistent-volumes-claims.vue, bcs-app/frontend/src/views/mc/event-query.vue, bcs-app/frontend/src/views/storage/pvc.vue
=> chore: 国际化

bcs-app/backend/iam/permissions/resources/templateset.py, bcs-app/backend/tests/conftest.py, bcs-app/backend/tests/iam/fake_iam.py, bcs-app/backend/tests/iam/permissions/conftest.py, bcs-app/backend/tests/iam/permissions/roles.py, bcs-app/backend/tests/iam/permissions/test_templateset.py
变更点(Changes)
对接权限中心v3模板集后端鉴权接口完成
=> 对接权限中心v3模板集后端鉴权接口完成

bcs-app/backend/apps/constants.py, bcs-app/backend/container_service/clusters/open_apis/namespace.py, bcs-app/backend/helm/app/bcs_info_provider.py, bcs-app/backend/helm/app/views.py, bcs-app/backend/helm/toolkit/kubehelm/templates/inject_bcs_info.yaml, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/resources/k8s.py, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/serializers.py, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/views.py
变更点(Changes)
允许系统命名空间，删除平台注入的部分未使用的key
=> feat: allow k8s system namespace and delete injected keys

bcs-app/backend/container_service/clusters/views/cluster.py, bcs-app/backend/tests/container_service/clusters/views/cluster.py
=> feat: query cluster verion

bcs-app/backend/components/bcs/k8s_client.py
变更点(Changes)
当获取cluster context出现异常时，主动失效缓存
=> feat: invalidate cluster context cache

bcs-app/frontend/src/views/cluster/node-overview.vue
变更点(Changes)
fix: 修复节点详情容器列表分页错误问题
Fixes #
=> fix: 修复节点详情容器列表分页错误问题

bcs-app/frontend/.eslintrc.js, bcs-app/frontend/index-dev.html, bcs-app/frontend/index.html, bcs-app/frontend/src/router/app.js, bcs-app/frontend/src/router/cluster.js, bcs-app/frontend/src/router/configuration.js, bcs-app/frontend/src/router/crdcontroller.js, bcs-app/frontend/src/router/dashboard.js, bcs-app/frontend/src/router/depot.js, bcs-app/frontend/src/router/helm.js, bcs-app/frontend/src/router/hpa.js, bcs-app/frontend/src/router/index.js, bcs-app/frontend/src/router/log.js, bcs-app/frontend/src/router/mc.js, bcs-app/frontend/src/router/metric.js, bcs-app/frontend/src/router/network.js, bcs-app/frontend/src/router/node.js, bcs-app/frontend/src/router/resource.js, bcs-app/frontend/src/router/storage.js
=> feature: mesos分离路由

bcs-app/frontend/build/config.js
=> minor: 删除config信息

bcs-app/frontend/src/components/ee-navigation.vue
=> fix: 修复项目管理跳转路由问题

bcs-app/frontend/src/views/helm/tpl-instance.vue
=> feature: chart部署简介跟着版本变化

bcs-app/backend/components/paas_cc.py, bcs-app/backend/iam/open_apis/provider/cluster.py, bcs-app/backend/iam/open_apis/provider/resource.py, bcs-app/backend/iam/open_apis/provider/templateset.py, bcs-app/backend/iam/open_apis/v1/urls.py, bcs-app/backend/templatesets/legacy_apps/configuration/utils.py, bcs-app/backend/tests/bcs_mocks/misc.py, bcs-app/backend/tests/iam/open_apis/test_cluster.py, bcs-app/backend/tests/iam/open_apis/test_templateset.py, bcs-app/backend/tests/templatesets/utils/__init__.py, bcs-app/backend/tests/templatesets/utils/conftest.py, bcs-app/backend/tests/templatesets/utils/test_utils.py, bcs-app/backend/tests/testing_utils/mocks/paas_cc.py
=> feature: 集群、模板集资源拉取接口

.gitignore, app_desc.yaml, bcs-cc/bin/post-compile, bcs-cc/bin/pre-compile, bcs-cc/config/dbconf.go
=> minor: update env name

bcs-app/frontend/src/common/lang.js, bcs-app/frontend/src/views/app/k8s/tmpl-instance.html, bcs-app/frontend/src/views/cluster/info.vue, bcs-app/frontend/src/views/variable/index.vue
变更点(Changes)
fix: 修复社区版1.5自验证问题
Fixes #
=> fix: 修复社区版1.5自验证问题

bcs-app/frontend/src/App.vue
变更点(Changes)
fix: 切换项目的时候重新reload窗口
Fixes #
=> fix: 切换项目的时候重新reload窗口

readme.md, readme_en.md
变更点(Changes)
更新BlueKing Community
=> docs: update BlueKing Community

bcs-app/frontend/src/views/configuration/namespace.vue, bcs-app/frontend/src/views/helm/tpl-instance.vue, bcs-app/frontend/src/views/helm/tpl-list.vue
1.命名空间展示资源配额
2.查询版本接口调用不准确，包含查询chart版本和release版本(区分内外版本)
=> fix: 私有化版本问题 to master

bcs-app/backend/components/paas_cc.py, bcs-app/backend/iam/open_apis/provider/cluster.py, bcs-app/backend/iam/open_apis/provider/namespace.py, bcs-app/backend/iam/open_apis/provider/project.py, bcs-app/backend/iam/open_apis/provider/templateset.py, bcs-app/backend/iam/perm_maker.py, bcs-app/backend/iam/permissions/apply_url.py, bcs-app/backend/iam/permissions/decorators.py, bcs-app/backend/iam/permissions/exceptions.py, bcs-app/backend/iam/permissions/perm.py, bcs-app/backend/iam/permissions/request.py, bcs-app/backend/iam/permissions/resources/__init__.py, bcs-app/backend/iam/permissions/resources/cluster.py, bcs-app/backend/iam/permissions/resources/namespace.py, bcs-app/backend/iam/permissions/resources/project.py, bcs-app/backend/iam/permissions/resources/templateset.py, bcs-app/backend/iam/request_maker.py, bcs-app/backend/iam/serializers.py, bcs-app/backend/iam/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/utils.py, bcs-app/backend/tests/iam/conftest.py, bcs-app/backend/tests/iam/permissions/conftest.py, bcs-app/backend/tests/iam/permissions/test_cluster.py, bcs-app/backend/tests/iam/permissions/test_namespace.py, bcs-app/backend/tests/iam/permissions/test_project.py, bcs-app/backend/tests/iam/permissions/test_templateset.py, bcs-app/backend/tests/iam/test_views.py, bcs-app/backend/tests/testing_utils/mocks/paas_cc.py, bcs-app/support-files/iam/0006_action_group.json
变更点(Changes)
重构user perms api接口
=> refactor: user perms api

bcs-app/backend/iam/permissions/perm.py, bcs-app/backend/iam/permissions/resources/cluster.py, bcs-app/backend/iam/permissions/resources/namespace.py, bcs-app/backend/iam/permissions/resources/project.py, bcs-app/backend/iam/permissions/resources/templateset.py, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/views.py
变更点(Changes)
给perm_ctx增加属性`resource_id`, `parent_resource_id`和方法`validate_resource_id`
=> refactor: resource perm ctx

bcs-app/backend/iam/permissions/decorators.py, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/views.py, bcs-app/backend/tests/iam/permissions/test_decorators.py, bcs-app/backend/utils/response.py
变更点(Changes)
新增PermsResponse，解决需要传递iam_path_attrs的问题
=> minor: add PermsResponse to reslove iam_path_attrs

bcs-app/backend/iam/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/namespace/views.py, bcs-app/backend/utils/response.py
=> refactor: namespace create perms

bcs-app/backend/container_service/clusters/utils.py, bcs-app/backend/container_service/clusters/views/cluster.py, bcs-app/backend/container_service/clusters/views/node.py, bcs-app/backend/container_service/clusters/views/node_views/operation_apis.py, bcs-app/backend/templatesets/legacy_apps/configuration/instance/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/showversion/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/utils.py, bcs-app/backend/templatesets/legacy_apps/configuration/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/yaml_mode/serializers.py, bcs-app/backend/templatesets/legacy_apps/configuration/yaml_mode/views.py
=> 集群、模板集业务侧iam鉴权

bcs-app/backend/iam/permissions/resources/cluster.py, bcs-app/backend/iam/permissions/resources/namespace.py, bcs-app/backend/iam/permissions/resources/project.py, bcs-app/backend/iam/permissions/resources/templateset.py
=> minor: not use cache when query iam policy

bcs-app/backend/iam/permissions/decorators.py, bcs-app/backend/settings/base.py, bcs-app/backend/utils/response.py
变更点(Changes)
add resource_data in PermsResponse
=> minor: add resource_data in PermsResponse

bcs-app/backend/iam/perm_maker.py, bcs-app/backend/iam/permissions/decorators.py, bcs-app/backend/iam/permissions/perm.py, bcs-app/backend/iam/permissions/request.py, bcs-app/backend/iam/permissions/resources/cluster.py, bcs-app/backend/iam/permissions/resources/namespace.py, bcs-app/backend/iam/permissions/resources/project.py, bcs-app/backend/iam/permissions/resources/templateset.py, bcs-app/backend/iam/request_maker.py, bcs-app/backend/iam/serializers.py, bcs-app/backend/iam/views.py, bcs-app/backend/tests/iam/test_views.py
变更点(Changes)
修复_bk_iam_path_作为类属性时的问题
=> fix: _bk_iam_path_ conflicts

bcs-app/backend/tests/container_service/clusters/open_apis/test_namespace.py
=> fix: fix namespace api unit test

bcs-app/backend/container_service/clusters/utils.py, bcs-app/backend/container_service/clusters/views/cluster.py, bcs-app/backend/container_service/clusters/views/node.py, bcs-app/backend/container_service/clusters/views/node_views/nodes.py, bcs-app/backend/templatesets/legacy_apps/configuration/views.py
变更点(Changes)
调整集群和模板集list接口返回值；给现在使用的节点设置标签接口添加iam权限
=> minor: 调整集群和模板集list接口返回值

bcs-app/backend/templatesets/legacy_apps/configuration/namespace/views.py
变更点(Changes)
修复missing ClusterPermCtx instance argument
=> minor: fix create ns

bcs-app/backend/utils/response.py
变更点(Changes)
PermResponse中resource_data取值问题。排除[]等情况
=> minor: PermResponse中resource_data取值问题

bcs-app/backend/iam/permissions/request.py, bcs-app/backend/iam/permissions/resources/templateset.py
=> minor: 转换模板集id格式为字符串

bcs-app/frontend/src/App.vue, bcs-app/frontend/src/mixins/authority.ts, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/k8s-create/yaml-mode/index.vue, bcs-app/frontend/src/views/configuration/templateset.vue, bcs-app/frontend/src/views/node/index.vue
=> fix: 权限中心问题修复

bcs-app/backend/iam/permissions/resources/templateset.py, bcs-app/support-files/iam/0007_resource_creator_actions.json
变更点(Changes)
关联权限新增templateset_copy；actions接口过滤template_id为0的情况
=> minor: 关联权限新增templateset_copy,；template_id过滤为0的情况

bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/configuration/k8s-create/header.vue, bcs-app/frontend/src/views/configuration/templateset.vue
=> fix: 修复权限中心对接问题

bcs-app/backend/container_service/clusters/views/cluster.py, bcs-app/backend/templatesets/legacy_apps/configuration/showversion/views.py, bcs-app/backend/templatesets/legacy_apps/configuration/views.py, bcs-app/support-files/iam/0006_action_group.json
变更点(Changes)
解决iam对接中集群、模板集部分问题
=> minor: iam涉及模板集、集群部分代码调整

bcs-app/backend/container_service/projects/base/__init__.py
=> Remove cluster type and project kind

bcs-app/backend/container_service/clusters/views/cluster.py, bcs-app/backend/settings/base.py
变更点(Changes)
优化创建集群视图内变量名，返回新建集群数据
=> minor: 优化创建集群视图内变量名，返回新建集群数据

bcs-app/backend/templatesets/legacy_apps/configuration/namespace/serializers.py
=> Update remove codes

bcs-app/backend/container_service/clusters/constants.py, bcs-app/backend/utils/views.py
=> feat: update project kin

bcs-app/frontend/src/views/network/loadbalance/mesos/index.vue
fix: 修复mesos loadbalance新建时重复发获取命名空间请求和切换集群后configmaplist未更新问题
=> fix: 修复mesos loadbalance新建时重复发获取命名空间请求和切换集群后configmaplist未更新问题

bcs-app/frontend/src/json/k8s-service.json, bcs-app/frontend/src/views/configuration/k8s-create/service.vue
=> fix: 修复service模板集ClusterIP逻辑

bcs-app/frontend/src/components/bcs-unregistry/unregistry.vue, bcs-app/frontend/src/views/cluster/index.vue
=> fix: 修复mesos逻辑删除后测试问题

bcs-app/frontend/src/views/cluster/node-overview.vue, bcs-app/frontend/src/views/cluster/overview.vue
=> fix: memory_usage字段变动

bcs-app/frontend/src/views/cluster/index.vue
=> fix: 概览页memory_usage字段变更

bcs-app/backend/templatesets/legacy_apps/configuration/models/template.py, bcs-app/backend/uniapps/apis/applications/views.py, bcs-app/backend/uniapps/apis/utils.py, bcs-app/backend/uniapps/application/all_views/views.py, bcs-app/backend/uniapps/application/base_views.py, bcs-app/backend/uniapps/application/instance_views.py, bcs-app/backend/uniapps/application/views.py
=> feat: remove legacy project kind code

bcs-app/frontend/src/views/helm/index.vue, bcs-app/frontend/src/views/helm/tpl-instance.vue, bcs-app/frontend/src/views/resource/ingress/k8s/index.vue
=> helm release页面的过滤问题

bcs-app/frontend/src/views/metric/main.vue
=> fix: metric折叠表格性能问题

bcs-app/frontend/src/views/helm/index.vue
=> fix: 修复helm release分页问题

bcs-app/frontend/src/views/node/index.vue
=> fix: 兼容节点污点字段可能为空的问题

bcs-app/frontend/src/views/configuration/templateset.vue
=> fix: 修复模板集点击加载更多时权限判断异常问题

bcs-app/frontend/src/views/mc/event-query.vue
=> fix: 事件中心中选择每页显示数目后表格没有刷新

bcs-app/frontend/src/views/cluster/overview.vue
=> optimization: 优化集群总览接口调用逻辑

bcs-app/frontend/src/views/app/list.css, bcs-app/frontend/src/views/app/mesos/tmpl-list.html
=> fix: mesos应用样式优化

bcs-app/frontend/build/webpack.prod.conf.js, bcs-app/frontend/src/views/cluster/container.vue
fix: 容器指标项参数更改 res_id_list -> container_ids
=> fix: 容器指标项参数更改 res_id_list -> container_ids

bcs-app/frontend/src/views/app/k8s/daemonset.vue, bcs-app/frontend/src/views/app/k8s/deployments.vue, bcs-app/frontend/src/views/app/k8s/job.vue, bcs-app/frontend/src/views/app/k8s/statefulset.vue, bcs-app/frontend/src/views/app/mixins/mixin-base-instantiation.js, bcs-app/frontend/src/views/configuration/instantiation.vue
=> fix: 修复私有化1.5.4测试问题

bcs-app/frontend/src/store/modules/k8s-template.js, bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue
=> fix: 修复模板集校验端口校验提示问题

bcs-app/frontend/src/views/configuration/k8s-create/daemonset.vue, bcs-app/frontend/src/views/configuration/k8s-create/deployment.vue, bcs-app/frontend/src/views/configuration/k8s-create/job.vue, bcs-app/frontend/src/views/configuration/k8s-create/statefulset.vue, bcs-app/frontend/src/views/configuration/mesos-create/application.vue
fix: 去除Mesos模板集在初始化时校验端口是否被关联问题
=> fix: 去除Mesos模板集在初始化时校验端口是否被关联问题

bcs-app/frontend/src/components/ip-selector/ip-selector-bcs.vue, bcs-app/frontend/src/components/ip-selector/ip-selector.css, bcs-app/frontend/src/components/ip-selector/ip-selector.js
fix: 修复IP选择器体验问题：1、跨页全选没有携带模块ID 2、自定义输入默认开启精确搜索
=> fix: 修复IP选择器体验问题：1、跨页全选没有携带模块ID 2、自定义输入默认开启精确搜索

bcs-app/frontend/src/components/ip-selector/ip-selector-bcs.vue, bcs-app/frontend/src/components/ip-selector/selector-dialog.vue, bcs-app/frontend/src/views/cluster/mixin-node.js
=> fix: 修复IP选择器体验问题

bcs-app/frontend/src/components/ip-selector/ip-selector-bcs.vue
=> fix: 机架换成机型

bcs-app/frontend/src/components/ip-selector/ip-selector-bcs.vue, bcs-app/frontend/src/components/ip-selector/ip-selector.css, bcs-app/frontend/src/components/ip-selector/ip-selector.js, bcs-app/frontend/src/components/tip-dialog/index.vue, bcs-app/frontend/src/views/cluster/mixin-node.js, bcs-app/frontend/src/views/cluster/node.vue
optimization: 添加节点二次确认按钮添加loading效果
=> optimization: 添加节点二次确认按钮添加loading效果

bcs-app/frontend/src/api/base.js, bcs-app/frontend/src/components/bcs-log/index.tsx, bcs-app/frontend/src/components/bcs-log/layout/log-header.tsx, bcs-app/frontend/src/components/bcs-log/style/log.scss, bcs-app/frontend/src/css/app.css, bcs-app/frontend/src/store/modules/dashboard.js, bcs-app/frontend/src/views/app/k8s/tmpl-instance.html, bcs-app/frontend/src/views/app/mixins/mixin-base-instance.js, bcs-app/frontend/src/views/dashboard/common/metric.vue, bcs-app/frontend/src/views/dashboard/workload/detail/pod-detail.vue, bcs-app/frontend/src/views/dashboard/workload/detail/workload-detail.vue
=> feature: 资源视图添加日志功能

bcs-app/frontend/src/components/bcs-log/layout/log-content.tsx, bcs-app/frontend/src/views/dashboard/common/base-layout.tsx
change: optimization: 优化命名空间和crd下拉缓存逻辑 & fix: 修复日志Hover背景在滚动加载时残留问题
=> change: optimization: 优化命名空间和crd下拉缓存逻辑 & fix: 修复日志Hover背景在滚动加载时残留问题

bcs-app/frontend/src/views/dashboard/common/base-layout.tsx
=> fix: 修复创建自定义资源时URL未携带crd参数的问题

bcs-app/backend/web_console/pod_life_cycle.py, bcs-app/backend/web_console/rest_api/views.py
变更点(Changes)
修复webconsole token无效的问题(render_to_string高版本对bytes渲染有特殊字符Q&#x27;)
=> fix: webconsole token invalid

bcs-app/frontend/src/views/cluster/info.vue
fix: 集群信息界面 mem_usage -> memory_usage
=> fix: 集群信息界面 mem_usage -> memory_usage

bcs-app/backend/bcs_web/apis/permissions.py, bcs-app/backend/settings/base.py, bcs-app/backend/utils/whitelist.py
变更点(Changes)
更新校验访问webconsole api的权限方式
=> feat: update perm for access webconsole api

bcs-app/frontend/src/views/index.vue
fix: 修复在未开启容器服务的项目上切换到mesos项目时未刷新界面问题
=> fix: 修复在未开启容器服务的项目上切换到mesos项目时未刷新界面问题

bcs-app/frontend/src/components/bcs-unregistry/unregistry.vue
=> fix: 开通容器服务业务类型样式调整

bcs-app/frontend/package.json, bcs-app/frontend/src/App.vue
=> fix: 修复ce版本构建报错问题

readme.md
=> update: readme
